--ALTER TABLE PURCHASE_MASTER ADD PO_ID INT
--ALTER TABLE PURCHASE_MASTER ADD TERM CHAR

--ALTER TABLE SALE_MASTER ADD SO_ID INT
--ALTER TABLE SALE_MASTER ADD TERM CHAR
--ALTER TABLE SALE_MASTER ADD BILL_NO NVARCHAR(50)

--ALTER TABLE SALE_RETURN_MASTER ADD SI_ID INT
--ALTER TABLE SALE_RETURN_MASTER ADD TERM CHAR

--ALTER TABLE SALE_DETAIL ADD GST FLOAT
--ALTER TABLE SALE_RETURN_DETAIL ADD GST FLOAT

CREATE TABLE PURCHASE_RETURN_MASTER(
ID INT IDENTITY(1,1) PRIMARY KEY,
INVOICE_NO NVARCHAR(50),
[DATE] DATETIME,
SUPPLIER_ID INT,
[DESCRIPTION] NVARCHAR(MAX),
CREATION_DATE DATETIME,
CREATED_BY INT,
MODIFICATION_DATE DATETIME,
MODIFIED_BY INT
)

CREATE TABLE PURCHASE_RETURN_DETAIL(
ID INT IDENTITY(1,1) PRIMARY KEY,
PURCHASE_RETURN_MASTER_ID INT,
MATERIAL_ID INT,
QTY FLOAT,
RATE FLOAT
)