DROP Database [BROKER_MANAGEMENT_SYSTEM_2023_24]
GO
USE [master]
GO
/****** Object:  Database [BROKER_MANAGEMENT_SYSTEM_2023_24]    Script Date: 11/06/2024 1:44:19 AM ******/
CREATE DATABASE [BROKER_MANAGEMENT_SYSTEM_2023_24]
USE [BROKER_MANAGEMENT_SYSTEM_2023_24]
GO
/****** Object:  UserDefinedFunction [dbo].[DeleteMaterial]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Abdul Haseeb
-- Create date: 23-08-2021
-- Description:	Delete Account
-- =============================================
CREATE FUNCTION [dbo].[DeleteMaterial] 
(
	@materialId int
)
RETURNS bit
AS
BEGIN
	DECLARE @result bit = 0;
	
	IF EXISTS( SELECT MATERIAL_ID FROM MATERIAL_ITEM_LEDGER WHERE MATERIAL_ID = @materialId AND ENTRY_FROM NOT LIKE '%OPENING%' )
	BEGIN
		SET @result = 1;
	END

	--IF EXISTS( SELECT COA_ID FROM SUPPLIER_PROFILE WHERE COA_ID = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END

	--IF EXISTS( SELECT COA_ID FROM LEDGERS WHERE COA_ID = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END
	
	--IF EXISTS( SELECT SUPPLIER_ID FROM PURCHASES_ORDER WHERE SUPPLIER_ID = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END		
	
	IF EXISTS( SELECT MATERIAL_ID FROM PURCHASE_DETAIL WHERE MATERIAL_ID = @materialId )
	BEGIN
		SET @result = 1;
	END
	
	IF EXISTS( SELECT MATERIAL_ID FROM JOB_ORDER_MATERIALS WHERE MATERIAL_ID = @materialId )
	BEGIN
		SET @result = 1;
	END
	
	IF EXISTS( SELECT ITEM_ID FROM SALE_DETAIL WHERE ITEM_ID = @materialId AND ITEM_TYPE = 'R' )
	BEGIN
		SET @result = 1;
	END
	
	--IF EXISTS( SELECT CUSTOMER_ID FROM SALES_RETURN_MASTER WHERE CUSTOMER_ID = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END
	
	--IF EXISTS( SELECT REC_AC FROM PAYMENT_TRANSFER WHERE REC_AC = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END
	
	--IF EXISTS( SELECT PAY_AC FROM PAYMENT_TRANSFER WHERE PAY_AC = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END	
	
	RETURN @result;
END

GO
/****** Object:  UserDefinedFunction [dbo].[DeleteProduct]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Abdul Haseeb
-- Create date: 23-08-2021
-- Description:	Delete Account
-- =============================================
CREATE FUNCTION [dbo].[DeleteProduct] 
(
	@productId int
)
RETURNS bit
AS
BEGIN
	DECLARE @result bit = 0;

	IF EXISTS( SELECT PRODUCT_ID FROM PRODUCT_ITEM_LEDGER WHERE PRODUCT_ID = @productId AND ENTRY_FROM NOT LIKE '%OPENING%' )
	BEGIN
		SET @result = 1;
	END

	--IF EXISTS( SELECT COA_ID FROM SUPPLIER_PROFILE WHERE COA_ID = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END

	--IF EXISTS( SELECT COA_ID FROM LEDGERS WHERE COA_ID = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END
	
	--IF EXISTS( SELECT SUPPLIER_ID FROM PURCHASES_ORDER WHERE SUPPLIER_ID = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END		

	--IF EXISTS( SELECT SUPPLIER_ID FROM PURCHASES_MASTER WHERE SUPPLIER_ID = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END

	--IF EXISTS( SELECT CUSTOMER_ID FROM SALES_ORDER_DIRECT WHERE CUSTOMER_ID = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END

	--IF EXISTS( SELECT CUSTOMER_ID FROM SALES WHERE CUSTOMER_ID = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END
	
	--IF EXISTS( SELECT CUSTOMER_ID FROM SALES_RETURN_MASTER WHERE CUSTOMER_ID = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END
	
	--IF EXISTS( SELECT REC_AC FROM PAYMENT_TRANSFER WHERE REC_AC = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END
	
	--IF EXISTS( SELECT PAY_AC FROM PAYMENT_TRANSFER WHERE PAY_AC = @coaId )
	--BEGIN
	--	SET @result = 1;
	--END	
	
	RETURN @result;
END

GO
/****** Object:  UserDefinedFunction [dbo].[GET_ACCOUNT_PARENT]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[GET_ACCOUNT_PARENT] 
(
	@NATURE VARCHAR(500)
)
RETURNS VARCHAR(100)
AS
BEGIN
	DECLARE @VALUE VARCHAR(100);

	IF(@NATURE = 'ACCOUNT RECEVIABLES' OR @NATURE = 'CURRENT ASSETS' OR @NATURE = 'ACCOUNT RECIVEABLE' OR @NATURE = 'ACUMALATED DEPRICIATION'
	   OR @NATURE = 'BANK' OR @NATURE = 'CASH' OR @NATURE = 'CUSTOMER'  OR @NATURE = 'MERCHANDISE INVENTORY')
		BEGIN
			SET @VALUE = 'CURRENT ASSETS';
		END
	ELSE IF(@NATURE = 'FIXED ASSETS')
		BEGIN
			SET @VALUE = 'FIXED ASSETS';
		END
	ELSE IF(@NATURE = 'ACCOUNT PAYABLE' OR @NATURE = 'BROKERS' OR @NATURE = 'CURRENT LAIBILITIES' OR @NATURE = 'VENDOR' OR @NATURE = 'OVERHEAD')
		BEGIN
			SET @VALUE = 'CURRENT LAIBILITIES';
		END
	ELSE IF(@NATURE = 'LONG TREM LAIBILITIES')
		BEGIN
			SET @VALUE = 'LONG TREM LAIBILITIES';
		END
	ELSE IF(@NATURE = 'ADMIN EXPENSES' OR @NATURE = 'DEPRICIATION EXP' OR @NATURE = 'GENERAL EXPENSES' OR @NATURE = 'TAX ACCOUNT')
		BEGIN
			SET @VALUE = 'EXPENSES';
		END
	ELSE IF(@NATURE = 'CAPITAL ACCOUNT')
		BEGIN
			SET @VALUE = 'CAPITAL ACCOUNTS';
		END
	ELSE IF(@NATURE = 'DRAWING ACCOUNT')
		BEGIN
			SET @VALUE = 'DRAWING';
		END
	ELSE IF(@NATURE = 'PURCHASES')
		BEGIN
			SET @VALUE = 'PURCHASES';
		END
	ELSE IF(@NATURE = 'SALES')
		BEGIN
			SET @VALUE = 'SALES';
		END
	ELSE IF(@NATURE = 'CURRENT YEAR INCOME' OR @NATURE = 'INCOME' OR @NATURE = 'PRIOR YEAR INCOME')
		BEGIN
			SET @VALUE = 'REVENUE';
		END
	RETURN @VALUE;
END



GO
/****** Object:  Table [dbo].[AA_SALES]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AA_SALES](
	[as_id] [int] IDENTITY(1,1) NOT NULL,
	[date] [datetime] NULL,
	[invoice_no] [varchar](max) NULL,
	[customer_id] [int] NULL,
	[so_id] [int] NULL,
	[sales_weight] [float] NULL,
	[balance_weight] [float] NULL,
	[kg_rate] [float] NULL,
	[muand_rate] [float] NULL,
	[total] [float] NULL,
	[credit_days] [int] NULL,
	[description] [text] NULL,
	[creation_date] [datetime] NULL,
	[created_by] [int] NULL,
	[modification_date] [datetime] NULL,
	[modification_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[as_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACCOUNT_GROUP]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCOUNT_GROUP](
	[AG_ID] [int] IDENTITY(1,1) NOT NULL,
	[AN_ID] [int] NULL,
	[PARENT_ID] [varchar](max) NULL,
	[AG_CODE] [varchar](max) NULL,
	[AG_NAME] [varchar](max) NULL,
	[LEVL] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[AG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACCOUNT_NATURE]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCOUNT_NATURE](
	[AN_ID] [int] IDENTITY(1,1) NOT NULL,
	[AN_CODE] [varchar](max) NULL,
	[AN_NAME] [varchar](max) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[AN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AREA]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AREA](
	[AREA_ID] [int] IDENTITY(1,1) NOT NULL,
	[AREA_NAME] [varchar](50) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[CITY_ID] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[AREA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BANK_BOOK]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BANK_BOOK](
	[BB_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[REC_AC] [int] NULL,
	[PAY_AC] [int] NULL,
	[AMOUNT] [float] NULL,
	[CHQ_ID] [int] NULL,
	[INSTRUMENT] [varchar](150) NULL,
	[NARRATION] [varchar](max) NULL,
	[REF_AC] [varchar](255) NULL,
 CONSTRAINT [PK_BANK_BOOK] PRIMARY KEY CLUSTERED 
(
	[BB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BANK_PAY_VOUCHER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BANK_PAY_VOUCHER](
	[BPV_ID] [int] IDENTITY(1,1) NOT NULL,
	[BPV_CODE] [varchar](max) NULL,
	[TRANS_CODE] [varchar](max) NULL,
	[DAATE] [datetime] NULL,
	[BANK_ID] [int] NULL,
	[COA_ID] [int] NULL,
	[ACCOUNT_OF] [varchar](max) NULL,
	[CHQ_NO] [varchar](max) NULL,
	[CHQ_DAATE] [datetime] NULL,
	[AMOUNT] [float] NULL,
	[PAID_TO] [varchar](max) NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BPV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BANK_PROFILE]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BANK_PROFILE](
	[BANK_PRO] [int] IDENTITY(1,1) NOT NULL,
	[COA_ID] [int] NULL,
	[AC_NUMBER] [varchar](max) NULL,
	[AC_TITLE] [varchar](max) NULL,
	[BRANCH_CODE] [varchar](max) NULL,
	[PHONE] [varchar](max) NULL,
	[MOBILE] [varchar](max) NULL,
	[EMAIL] [varchar](max) NULL,
	[ADDRESS] [varchar](max) NULL,
	[CITY_ID] [int] NULL,
	[CREDIT_LIMIT] [float] NULL,
	[CONTACT_PERSON] [varchar](max) NULL,
	[STAT] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BANK_PRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BANK_REC_VOUCHER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BANK_REC_VOUCHER](
	[BRV_ID] [int] IDENTITY(1,1) NOT NULL,
	[BRV_CODE] [varchar](max) NULL,
	[TRANS_CODE] [varchar](max) NULL,
	[DAATE] [datetime] NULL,
	[BANK_ID] [int] NULL,
	[COA_ID] [int] NULL,
	[ACCOUNT_OF] [varchar](max) NULL,
	[CHQ_NO] [varchar](max) NULL,
	[CHQ_DAATE] [datetime] NULL,
	[AMOUNT] [float] NULL,
	[REC_FROM] [varchar](max) NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BRV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BANK_TRANSFER_VOUCHER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BANK_TRANSFER_VOUCHER](
	[BTV_ID] [int] IDENTITY(1,1) NOT NULL,
	[BTV_CODE] [varchar](max) NULL,
	[TRANS_CODE] [varchar](max) NULL,
	[DAATE] [datetime] NULL,
	[FROM_BANK_ID] [int] NULL,
	[TO_BANK_ID] [int] NULL,
	[NARRATION] [varchar](max) NULL,
	[CHQ_NO] [varchar](max) NULL,
	[CHQ_DAATE] [datetime] NULL,
	[AMOUNT] [float] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BTV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BROKER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BROKER](
	[BROKER_ID] [int] IDENTITY(1,1) NOT NULL,
	[COA_ID] [int] NULL,
	[NAME] [varchar](max) NULL,
	[MOBILE] [varchar](max) NULL,
	[EMAIL] [varchar](max) NULL,
	[CITY_ID] [int] NULL,
	[COMMISSION_VALUE] [float] NULL,
	[COMISSION_TYPE] [int] NULL,
	[STAT] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BROKER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CARTAGE_PACKING]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CARTAGE_PACKING](
	[CP_ID] [int] IDENTITY(1,1) NOT NULL,
	[CP_NAME] [varchar](100) NULL,
	[CP_RATE] [float] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_ID] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[CP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CASH_PAY_VOUCHER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CASH_PAY_VOUCHER](
	[CPV_ID] [int] IDENTITY(1,1) NOT NULL,
	[CPV_CODE] [varchar](max) NULL,
	[TRANS_CODE] [varchar](max) NULL,
	[DAATE] [datetime] NULL,
	[COA_ID] [int] NULL,
	[ACCOUNT_OF] [varchar](max) NULL,
	[AMOUNT] [float] NULL,
	[PAID_TO] [varchar](max) NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
	[REF_ACCOUNT] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[CPV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CASH_REC_VOUCHER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CASH_REC_VOUCHER](
	[CRV_ID] [int] IDENTITY(1,1) NOT NULL,
	[CRV_CODE] [varchar](max) NULL,
	[TRANS_CODE] [varchar](max) NULL,
	[FOLIO] [varchar](max) NULL,
	[DAATE] [datetime] NULL,
	[COA_ID] [int] NULL,
	[DESCRIPTION] [varchar](max) NULL,
	[AMOUNT] [float] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
	[REF_ACCOUNT] [varchar](500) NULL,
	[REC_PERSON_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CRV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CASH_VOUCHER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CASH_VOUCHER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VOUCHER_TYPE] [char](1) NULL,
	[VOUCHER_NUMBER] [nvarchar](50) NULL,
	[DATE] [datetime] NULL,
	[ACCOUNT_ID] [int] NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
	[AMOUNT] [float] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHQ]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHQ](
	[CHQ_ID] [int] IDENTITY(1,1) NOT NULL,
	[CHQ_DATE] [datetime] NULL,
	[CHQ_NO] [varchar](max) NULL,
	[AMOUNT] [float] NULL,
	[REC_AC] [int] NULL,
	[PAY_AC] [int] NULL,
	[BANK_NAME] [varchar](100) NULL,
	[STATUS] [char](1) NULL,
	[PAY_DATE] [datetime] NULL,
	[REC_DATE] [datetime] NULL,
 CONSTRAINT [PK__CHQ__534199BB418392DF] PRIMARY KEY CLUSTERED 
(
	[CHQ_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHQ_BOOKS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHQ_BOOKS](
	[CHQ_BOOK_ID] [int] IDENTITY(1,1) NOT NULL,
	[COA_ID] [int] NULL,
	[BOOK_NUMBER] [varchar](max) NULL,
	[NUMBER_OF_CHQS] [int] NULL,
	[STAT] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CHQ_BOOK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHQ_BOOKS_SLIPS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHQ_BOOKS_SLIPS](
	[CHQ_SLIP_ID] [int] IDENTITY(1,1) NOT NULL,
	[CHQ_BOOK_ID] [int] NULL,
	[SLIP_NUMBER] [varchar](max) NULL,
	[STAT] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CHQ_SLIP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHQ_RETURN_HISTORY]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHQ_RETURN_HISTORY](
	[DATE] [datetime] NULL,
	[CHQ_ID] [int] NULL,
	[REMARKS] [text] NULL,
	[REC_AC] [int] NULL,
	[PAY_AC] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CITY]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CITY](
	[CITY_ID] [int] IDENTITY(1,1) NOT NULL,
	[CITY_NAME] [varchar](50) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[REG_ID] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COA]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COA](
	[COA_ID] [int] IDENTITY(1,1) NOT NULL,
	[AG_ID] [int] NULL,
	[CA_ID] [int] NULL,
	[COA_CODE] [varchar](max) NULL,
	[COA_NAME] [varchar](max) NULL,
	[OPEN_BAL] [float] NULL,
	[DR_CR] [char](1) NULL,
	[STAT] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
	[rateType] [char](1) NULL,
	[CITY_ID] [int] NULL,
	[AREA_ID] [int] NULL,
	[MOBILE] [nvarchar](20) NULL,
	[EMAIL] [nvarchar](500) NULL,
	[ADDRESS] [nvarchar](max) NULL,
	[CREDIT_DAYS] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[COA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COMPANY]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPANY](
	[COMPANY_ID] [int] IDENTITY(1,1) NOT NULL,
	[COMPANY_NAME] [varchar](max) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[COMPANY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COMPANY_PROFILE]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPANY_PROFILE](
	[COM_PRO_ID] [int] IDENTITY(1,1) NOT NULL,
	[COMPANY_ID] [int] NULL,
	[NTN_NUMBER] [varchar](max) NULL,
	[STRN_NUMBER] [varchar](max) NULL,
	[GST_NUMBER] [varchar](max) NULL,
	[PHONE] [varchar](max) NULL,
	[MOBILE] [varchar](max) NULL,
	[EMAIL] [varchar](max) NULL,
	[WEBISTE] [varchar](max) NULL,
	[ADDRESS] [varchar](max) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[COM_PRO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTROL_ACCOUNT]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTROL_ACCOUNT](
	[CA_ID] [int] IDENTITY(1,1) NOT NULL,
	[CA_NAME] [varchar](max) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
	[AN_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMER_PROFILE]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER_PROFILE](
	[CUST_PRO] [int] IDENTITY(1,1) NOT NULL,
	[COA_ID] [int] NULL,
	[SALE_PER_ID] [int] NULL,
	[CONTACT_PERSON] [varchar](max) NULL,
	[MOBILE] [varchar](max) NULL,
	[EMAIL] [varchar](max) NULL,
	[ADDRESS] [varchar](max) NULL,
	[CITY_ID] [int] NULL,
	[NTN_NUMBER] [varchar](max) NULL,
	[STRN_NUMBER] [varchar](max) NULL,
	[GST_NUMBER] [varchar](max) NULL,
	[CREDIT_LIMIT] [float] NULL,
	[AREA_ID] [int] NULL,
	[STAT] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
	[CREDIT_DAYS] [int] NULL,
	[CNIC] [varchar](20) NULL,
	[EXPIRY] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[CUST_PRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DAY_BOOK]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DAY_BOOK](
	[DAY_BOOK_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[ENTRY_OF] [varchar](100) NULL,
	[DEBIT_AC] [int] NULL,
	[CREDIT_AC] [int] NULL,
	[AMOUMT] [float] NULL,
	[DESCRIPTION] [varchar](500) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[CASH_AMOUNT] [float] NULL,
	[BANK_AMOUNT] [float] NULL,
	[REC_PERSON_ID] [int] NULL,
	[PAID_TO] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[DAY_BOOK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DAY_BOOK_CHQ]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DAY_BOOK_CHQ](
	[DBC_ID] [int] IDENTITY(1,1) NOT NULL,
	[CHQ_ID] [int] NULL,
	[DAY_BOOK_ID] [int] NULL,
	[TYPE] [char](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FORMULA_TYPE]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FORMULA_TYPE](
	[FT_ID] [int] IDENTITY(1,1) NOT NULL,
	[FT_NAME] [varchar](100) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GATE_PASS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GATE_PASS](
	[GPM_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[SOP_ID] [int] NULL,
	[INVOICE_NO] [varchar](50) NULL,
	[DESCRIPTION] [text] NULL,
	[VEHICLE_NO] [varchar](50) NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_ID] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MUAND_RATE] [text] NULL,
	[SALES_ORDER_ID] [int] NULL,
	[SO_TYPE] [char](1) NULL,
	[GP_TYPE] [char](1) NULL,
	[TOTAL_WEIGHT] [float] NULL,
	[AMOUNT] [float] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GATE_PASS_DETAIL]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GATE_PASS_DETAIL](
	[GPD_ID] [int] IDENTITY(1,1) NOT NULL,
	[GP_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[QTY] [float] NULL,
	[RATE] [float] NULL,
	[ITEM_TYPE] [char](1) NULL,
	[WEIGHT] [float] NULL,
	[MILLING_RATE] [float] NULL,
	[PACKING_RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GENERAL_VOUCHER_D]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GENERAL_VOUCHER_D](
	[GVD_ID] [int] IDENTITY(1,1) NOT NULL,
	[GV_ID] [int] NULL,
	[COA_ID] [int] NULL,
	[DEBIT] [float] NULL,
	[CREDIT] [float] NULL,
	[NARRATION] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[GVD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GENERAL_VOUCHER_M]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GENERAL_VOUCHER_M](
	[GV_ID] [int] IDENTITY(1,1) NOT NULL,
	[GV_CODE] [varchar](max) NULL,
	[TRANS_CODE] [varchar](max) NULL,
	[DAATE] [datetime] NULL,
	[NARRATION] [varchar](max) NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[GV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVENTORY_ADJUSTMENTS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVENTORY_ADJUSTMENTS](
	[IA_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[MATERIAL_ID] [int] NULL,
	[ADD_LESS] [char](1) NULL,
	[QTY] [float] NULL,
	[RATE] [float] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVENTORY_ADJUSTMENTS_RAW]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVENTORY_ADJUSTMENTS_RAW](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[MATERIAL_ID] [int] NULL,
	[ADD_LESS] [char](1) NULL,
	[QTY] [float] NULL,
	[RATE] [float] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ISSUANCE_DETAIL]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ISSUANCE_DETAIL](
	[ISSUANCE_DETAIL] [int] IDENTITY(1,1) NOT NULL,
	[ISSUANCE_MASTER_ID] [int] NULL,
	[ITEM_TYPE] [char](1) NULL,
	[ITEM_ID] [int] NULL,
	[QTY] [float] NULL,
	[RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ISSUANCE_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ISSUANCE_MASTER](
	[ISSUANCE_MASTER_ID] [int] IDENTITY(1,1) NOT NULL,
	[INVOICE_NO] [varchar](100) NULL,
	[DATE] [datetime] NULL,
	[ACCOUNT_ID] [int] NULL,
	[VEHICLE_NO] [varchar](100) NULL,
	[DESCRIPTION] [text] NULL,
	[CREDIT_DAYS] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOB_ORDER_EXPENSES]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_ORDER_EXPENSES](
	[JOB_ORDER_EXPENSES_ID] [int] IDENTITY(1,1) NOT NULL,
	[JOB_ORDER_MASTER_ID] [int] NULL,
	[DATE] [datetime] NULL,
	[EXPENSE_ID] [int] NULL,
	[DESCRIPTION] [text] NULL,
	[AMOUNT] [float] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOB_ORDER_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_ORDER_MASTER](
	[JOB_ORDER_MASTER_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[DESCRIPTION] [text] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[STATUS] [char](1) NULL,
	[INVOICE_NO] [varchar](100) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOB_ORDER_MATERIAL_EXPENSES]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_ORDER_MATERIAL_EXPENSES](
	[JOB_ORDER_MATERIAL_EXPENSES_ID] [int] IDENTITY(1,1) NOT NULL,
	[JOB_ORDER_MASTER_ID] [int] NULL,
	[DATE] [datetime] NULL,
	[EXPENSE_ID] [int] NULL,
	[ACCOUNT_ID] [int] NULL,
	[DESCRIPTION] [text] NULL,
	[MATERIAL_ID] [int] NULL,
	[QTY] [int] NULL,
	[AMOUNT] [float] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[REC_QTY] [float] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOB_ORDER_MATERIALS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_ORDER_MATERIALS](
	[JOB_ORDER_MATERIAL_ID] [int] IDENTITY(1,1) NOT NULL,
	[JOB_ORDER_PRODUCT_ID] [int] NULL,
	[MATERIAL_ID] [int] NULL,
	[QTY] [int] NULL,
	[JOB_ORDER_MASTER_ID] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOB_ORDER_PRODUCTS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_ORDER_PRODUCTS](
	[JOB_ORDER_PRODUCT_ID] [int] IDENTITY(1,1) NOT NULL,
	[JOB_ORDER_MASTER_ID] [int] NULL,
	[PRODUCT_MASTER_ID] [int] NULL,
	[QTY] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LEDGERS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LEDGERS](
	[LEGDER_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[COA_ID] [int] NULL,
	[REF_ID] [int] NULL,
	[ENTRY_OF] [varchar](max) NULL,
	[FOLIO] [varchar](max) NULL,
	[DEBIT] [float] NULL,
	[CREDIT] [float] NULL,
	[DESCRIPTIONS] [varchar](max) NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
	[REF_AC_ID] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[LEGDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOCATION]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOCATION](
	[LOCATION_ID] [int] IDENTITY(1,1) NOT NULL,
	[LOCATION_NAME] [varchar](max) NULL,
	[CITY_ID] [int] NULL,
	[STAT] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[LOCATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOGS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOGS](
	[LOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[FORM_NAME] [varchar](max) NULL,
	[EVENT] [varchar](max) NULL,
	[FORM_PID] [varchar](max) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MATERIAL_ITEM_LEDGER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MATERIAL_ITEM_LEDGER](
	[MATERIAL_LED_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[MATERIAL_ID] [int] NULL,
	[REF_NO] [varchar](max) NULL,
	[ENTRY_FROM] [varchar](max) NULL,
	[STOCK_IN] [float] NULL,
	[STOCK_OUT] [float] NULL,
	[COST_AMT] [float] NULL,
	[SALE_AMT] [float] NULL,
	[L_ID] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MATERIAL_LED_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MATERIAL_TYPES]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MATERIAL_TYPES](
	[M_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[M_TYPE_NAME] [varchar](max) NULL,
	[STAT] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[M_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MATERIALS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MATERIALS](
	[MATERIAL_ID] [int] IDENTITY(1,1) NOT NULL,
	[M_TYPE_ID] [int] NULL,
	[LOCATION_ID] [int] NULL,
	[MATERIAL_CODE] [varchar](max) NULL,
	[MATERIAL_NAME] [varchar](max) NULL,
	[UNIT_ID] [int] NULL,
	[OPENING_QTY] [float] NULL,
	[OPENING_RATE] [float] NULL,
	[STAT] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
	[MIN_QTY] [float] NULL,
	[MAX_QTY] [float] NULL,
	[WEIGHT] [float] NULL,
	[QUALITY] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MATERIAL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAYMENT_TRANSFER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENT_TRANSFER](
	[PT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PV_NO] [varchar](100) NULL,
	[DATE] [datetime] NULL,
	[REC_AC] [int] NULL,
	[PAY_AC] [int] NULL,
	[REF_AC] [varchar](max) NULL,
	[CHQ_ONLINE] [char](1) NULL,
	[CHQ_DATE] [datetime] NULL,
	[AMOUNT] [float] NULL,
	[BANK] [varchar](100) NULL,
	[BR_CODE] [varchar](100) NULL,
	[INSTRUMENT_NO] [varchar](100) NULL,
	[STATUS] [char](1) NULL,
	[CONFORMATION_DATE] [datetime] NULL,
	[PERSON] [varchar](100) NULL,
	[REMARKS] [varchar](100) NULL,
	[SUB_ACC] [varchar](200) NULL,
	[CNIC] [varchar](30) NULL,
	[CHQ_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCT_CATEGORY]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCT_CATEGORY](
	[P_CATEGORY_ID] [int] IDENTITY(1,1) NOT NULL,
	[P_CATEEGORY_NAME] [varchar](max) NULL,
	[STAT] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[P_CATEGORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCT_DETAILS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCT_DETAILS](
	[PD_ID] [int] IDENTITY(1,1) NOT NULL,
	[PM_ID] [int] NULL,
	[M_TYPE_ID] [int] NULL,
	[MATERIAL_ID] [int] NULL,
	[WEIGHT] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCT_ITEM_LEDGER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCT_ITEM_LEDGER](
	[PRODUCT_LED_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[PRODUCT_ID] [int] NULL,
	[REF_NO] [varchar](max) NULL,
	[ENTRY_FROM] [varchar](max) NULL,
	[STOCK_IN] [float] NULL,
	[STOCK_OUT] [float] NULL,
	[COST_AMT] [float] NULL,
	[SALE_AMT] [float] NULL,
	[L_ID] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PRODUCT_LED_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCT_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCT_MASTER](
	[PM_ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCT_CODE] [varchar](500) NULL,
	[PRODUCT_NAME] [varchar](500) NULL,
	[GROSS_WEIGHT] [float] NULL,
	[NET_WEIGHT] [float] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[BRAND_ID] [int] NULL,
	[CP_ID] [int] NULL,
	[MILLING_RATE] [float] NULL,
	[PACKING_RATE] [float] NULL,
	[OPENING_QTY] [float] NULL,
	[MIN_QTY] [float] NULL,
	[MAX_QTY] [float] NULL,
	[OPENING_RATE] [float] NULL,
	[LIST_RATE] [float] NULL,
	[NET_RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTION_DETAIL]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTION_DETAIL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCTION_MASTER_ID] [int] NULL,
	[PRODUCT_MASTER_ID] [int] NULL,
	[QTY] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTION_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTION_MASTER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductList30_10_2021]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductList30_10_2021](
	[ID] [float] NULL,
	[BRAND] [nvarchar](255) NULL,
	[PRODUCT CODE] [float] NULL,
	[PRODUCT NAME] [nvarchar](255) NULL,
	[OLD NET RATE] [float] NULL,
	[OLD LIST RATE] [float] NULL,
	[NEW NET RATE] [float] NULL,
	[NEW RETAIL RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductRates18122021]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductRates18122021](
	[ID] [float] NULL,
	[BRAND] [nvarchar](255) NULL,
	[PRODUCT CODE] [float] NULL,
	[PRODUCT NAME] [nvarchar](255) NULL,
	[OLD NET RATE] [float] NULL,
	[OLD LIST RATE] [float] NULL,
	[NEW NET RATE] [float] NULL,
	[NEW RETAIL RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products_15_2]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products_15_2](
	[PRODUCT_CODE] [nvarchar](255) NULL,
	[PRODUCT_NAME] [nvarchar](255) NULL,
	[MARSHAL ] [nvarchar](255) NULL,
	[BLUE FLAME ] [nvarchar](255) NULL,
	[MEHRAN ] [nvarchar](255) NULL,
	[PAK FAMOUS] [nvarchar](255) NULL,
	[NATURAL ] [nvarchar](255) NULL,
	[PAK] [nvarchar](255) NULL,
	[SUN FLAME] [nvarchar](255) NULL,
	[LIST RATE] [float] NULL,
	[NET RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTS_FORMULA]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTS_FORMULA](
	[PF_ID] [int] IDENTITY(1,1) NOT NULL,
	[FOURMULA_ID] [int] NULL,
	[CASH_CREDIT] [bit] NULL,
	[CUSTOMER_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[PACKING_RATE] [float] NULL,
	[MUAND_RATE] [float] NULL,
	[MILLING] [float] NULL,
	[CONSTANT_VALUE] [float] NULL,
	[KG_RATE] [float] NULL,
	[DIFFERENCE] [float] NULL,
	[ADDITION] [float] NULL,
	[2x] [float] NULL,
	[SALE_PRICE] [float] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PURCHASE_DETAIL]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PURCHASE_DETAIL](
	[PURCHASE_DETAIL] [int] IDENTITY(1,1) NOT NULL,
	[PURCHASE_MASTER_ID] [int] NULL,
	[MATERIAL_ID] [int] NULL,
	[QTY] [float] NULL,
	[RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PURCHASE_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PURCHASE_MASTER](
	[PURCHASE_MASTER_ID] [int] IDENTITY(1,1) NOT NULL,
	[INVOICE_NO] [varchar](100) NULL,
	[DATE] [datetime] NULL,
	[SUPPLIER_ID] [int] NULL,
	[DESCRIPTION] [text] NULL,
	[CREDIT_DAYS] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[PO_ID] [int] NULL,
	[TERM] [char](1) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PURCHASE_RETURN_DETAIL]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PURCHASE_RETURN_DETAIL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PURCHASE_RETURN_MASTER_ID] [int] NULL,
	[MATERIAL_ID] [int] NULL,
	[QTY] [float] NULL,
	[RATE] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PURCHASE_RETURN_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PURCHASE_RETURN_MASTER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[INVOICE_NO] [nvarchar](50) NULL,
	[DATE] [datetime] NULL,
	[SUPPLIER_ID] [int] NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PURCHASES]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PURCHASES](
	[PI_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[SUPPLIER_ID] [int] NULL,
	[PO_ID] [int] NULL,
	[VEHICLE_NO] [varchar](50) NULL,
	[DESCRIPTION] [text] NULL,
	[NET_WEIGHT] [float] NULL,
	[KORANGI_WEIGHT] [float] NULL,
	[KG_RATE] [float] NULL,
	[MUAND_RATE] [float] NULL,
	[MUAND_VALUE] [float] NULL,
	[CREDIT_DAYS] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[INVOICE_NO] [varchar](500) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PURCHASES_DETAILS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PURCHASES_DETAILS](
	[PURCHASES_DETAILS_ID] [int] IDENTITY(1,1) NOT NULL,
	[PI_ID] [int] NULL,
	[MATERIAL_ID] [int] NULL,
	[QTY] [int] NULL,
	[RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PURCHASES_ORDER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PURCHASES_ORDER](
	[PO_ID] [int] IDENTITY(1,1) NOT NULL,
	[PO_NUMBER] [varchar](100) NULL,
	[DATE] [datetime] NULL,
	[MATERIAL_ID] [int] NULL,
	[WEIGHT] [float] NULL,
	[SUPPLIER_ID] [int] NULL,
	[DESCRIPTION] [text] NULL,
	[KG_RATE] [float] NULL,
	[MUAND_RATE] [float] NULL,
	[MUAND_VALUE] [float] NULL,
	[CREDIT_DAYS] [int] NULL,
	[REC_WEIGHT] [float] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[STATUS] [char](1) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PURCHASES_ORDER_DETAILS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PURCHASES_ORDER_DETAILS](
	[PURCHASES_ORDER_DETAILS_ID] [int] IDENTITY(1,1) NOT NULL,
	[PO_ID] [int] NULL,
	[MATERIAL_ID] [int] NULL,
	[QTY] [int] NULL,
	[RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PURCHASES_PACKING_DETAILS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PURCHASES_PACKING_DETAILS](
	[PPDI_ID] [int] IDENTITY(1,1) NOT NULL,
	[PPM_ID] [int] NULL,
	[P_MATERIAL_ID] [int] NULL,
	[QTY] [float] NULL,
	[RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PURCHASES_PACKING_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PURCHASES_PACKING_MASTER](
	[PPMI_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[SUPPLIER_ID] [int] NULL,
	[VEHICLE_NO] [varchar](50) NULL,
	[DESCRIPTION] [text] NULL,
	[CREDIT_DAYS] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[TOTAL] [float] NULL,
	[INVOICE_NO] [varchar](500) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[purchases_sales_transfer]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[purchases_sales_transfer](
	[pst_id] [int] IDENTITY(1,1) NOT NULL,
	[date] [datetime] NULL,
	[purchases_id] [int] NULL,
	[customer_id] [int] NULL,
	[so_id] [int] NULL,
	[sales_weight] [float] NULL,
	[balance_weight] [float] NULL,
	[kg_rate] [float] NULL,
	[muand_rate] [float] NULL,
	[total] [float] NULL,
	[credit_days] [int] NULL,
	[description] [text] NULL,
	[creation_date] [datetime] NULL,
	[created_by] [int] NULL,
	[modification_date] [datetime] NULL,
	[modification_id] [int] NULL,
	[INVOICE_NO] [varchar](255) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PV_CHQS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PV_CHQS](
	[PVC_ID] [int] IDENTITY(1,1) NOT NULL,
	[DAY_BOOK_ID] [int] NULL,
	[CHQ_ID] [int] NULL,
	[PAY_AC] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PVC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RateUpdate17062022]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RateUpdate17062022](
	[ID] [float] NULL,
	[BRAND] [nvarchar](255) NULL,
	[PRODUCT CODE] [nvarchar](255) NULL,
	[PRODUCT NAME] [nvarchar](255) NULL,
	[OLD NET RATE] [float] NULL,
	[OLD LIST RATE] [float] NULL,
	[NEW NET RATE] [float] NULL,
	[NEW RETAIL RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RECOVERY_DETAILS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECOVERY_DETAILS](
	[REC_ID] [int] IDENTITY(1,1) NOT NULL,
	[REC_PERSON_ID] [int] NULL,
	[CUST_ID] [int] NULL,
	[CHQ_NO] [varchar](max) NULL,
	[CASH] [float] NULL,
	[CREATION_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[REC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RECOVERY_PERSON]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECOVERY_PERSON](
	[REC_PERSON_ID] [int] IDENTITY(1,1) NOT NULL,
	[REC_PERSON_NAME] [varchar](100) NULL,
 CONSTRAINT [PK_RECOVERY_PERSON] PRIMARY KEY CLUSTERED 
(
	[REC_PERSON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REGION]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REGION](
	[REGION_ID] [int] IDENTITY(1,1) NOT NULL,
	[REGION_NAME] [varchar](50) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[REGION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALE_DETAIL]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALE_DETAIL](
	[SALE_DETAIL] [int] IDENTITY(1,1) NOT NULL,
	[SALE_MASTER_ID] [int] NULL,
	[ITEM_TYPE] [char](1) NULL,
	[ITEM_ID] [int] NULL,
	[QTY] [float] NULL,
	[RATE] [float] NULL,
	[GST] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALE_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALE_MASTER](
	[SALE_MASTER_ID] [int] IDENTITY(1,1) NOT NULL,
	[INVOICE_NO] [varchar](100) NULL,
	[DATE] [datetime] NULL,
	[CUSTOMER_ID] [int] NULL,
	[VEHICLE_NO] [varchar](100) NULL,
	[DESCRIPTION] [text] NULL,
	[CREDIT_DAYS] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[TRANSPORTATION] [float] NULL,
	[SO_ID] [int] NULL,
	[TERM] [char](1) NULL,
	[BILL_NO] [nvarchar](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALE_RETURN_DETAIL]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALE_RETURN_DETAIL](
	[SALE_RETURN_DETAIL] [int] IDENTITY(1,1) NOT NULL,
	[SALE_RETURN_MASTER_ID] [int] NULL,
	[ITEM_TYPE] [char](1) NULL,
	[ITEM_ID] [int] NULL,
	[QTY] [float] NULL,
	[RATE] [float] NULL,
	[GST] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALE_RETURN_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALE_RETURN_MASTER](
	[SALE_RETURN_MASTER_ID] [int] IDENTITY(1,1) NOT NULL,
	[INVOICE_NO] [varchar](100) NULL,
	[DATE] [datetime] NULL,
	[CUSTOMER_ID] [int] NULL,
	[DESCRIPTION] [text] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[SI_ID] [int] NULL,
	[TERM] [char](1) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALES]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALES](
	[S_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[SOP_ID] [int] NULL,
	[INVOICE_NO] [varchar](50) NULL,
	[DESCRIPTION] [text] NULL,
	[VEHICLE_NO] [varchar](50) NULL,
	[REMAINING_AMOUNT] [float] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_ID] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MUAND_RATE] [text] NULL,
	[GPM_ID] [int] NULL,
	[CUSTOMER_ID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALES_ORDER_DIRECT]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALES_ORDER_DIRECT](
	[SOD_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[INVOICE_NO] [varchar](200) NULL,
	[CUSTOMER_ID] [int] NULL,
	[CREDIT_DAYS] [int] NULL,
	[DESCRIPTION] [text] NULL,
	[TOTAL_KGS] [float] NULL,
	[RATE] [float] NULL,
	[SALES_TYPE] [bit] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[REMAINING_WEIGHT] [float] NULL,
	[MATERIAL_ID] [int] NULL,
	[STATUS] [char](1) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALES_ORDER_PRODUCT_DETAILS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALES_ORDER_PRODUCT_DETAILS](
	[SOPD_ID] [int] IDENTITY(1,1) NOT NULL,
	[SOPM_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[QTY] [int] NULL,
	[RATE] [float] NULL,
	[WEIGHT] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALES_ORDER_PRODUCT_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALES_ORDER_PRODUCT_MASTER](
	[SOPM_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[CUSTOMER_ID] [int] NULL,
	[INVOICE_NO] [varchar](200) NULL,
	[DESCRIPTION] [varchar](max) NULL,
	[CREDIT_DAYS] [int] NULL,
	[TOTAL] [float] NULL,
	[TOTAL_WEIGHT] [float] NULL,
	[REMAINING_WEIGHT] [float] NULL,
	[COMPANY_ID] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[SALES_TYPE] [bit] NULL,
	[STATUS] [char](1) NULL,
	[MUAND_RATE] [text] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALES_PERSONS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALES_PERSONS](
	[SALES_PER_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](max) NULL,
	[MOBILE] [varchar](max) NULL,
	[EMAIL] [varchar](max) NULL,
	[CITY_ID] [int] NULL,
	[STAT] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
	[AREA_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[SALES_PER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALES_PROGRAM_DETAILS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALES_PROGRAM_DETAILS](
	[SPD_ID] [int] IDENTITY(1,1) NOT NULL,
	[SPM_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[QTY] [int] NULL,
	[RATE] [float] NULL,
	[ITEM_TYPE] [char](1) NULL,
	[WEIGHT] [float] NULL,
	[MILLING_RATE] [float] NULL,
	[PACKING_RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALES_PROGRAM_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALES_PROGRAM_MASTER](
	[SPM_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[CUSTOMER_ID] [int] NULL,
	[SOD_ID] [int] NULL,
	[INVOICE_NO] [varchar](200) NULL,
	[DESCRIPTION] [varchar](max) NULL,
	[TOTAL] [float] NULL,
	[TOTAL_WEIGHT] [float] NULL,
	[COMPANY_ID] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[REMAINING_WEIGHT] [float] NULL,
	[SO_TYPE] [char](1) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALES_RETURN_DETAIL]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALES_RETURN_DETAIL](
	[SRD_ID] [int] IDENTITY(1,1) NOT NULL,
	[SRM_ID] [int] NULL,
	[ITEM_ID] [int] NULL,
	[QTY] [int] NULL,
	[ITEM_WEIGHT] [float] NULL,
	[ITEM_RATE] [float] NULL,
	[ITEM_TYPE] [char](1) NULL,
	[MATERIAL_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[SRD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALES_RETURN_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALES_RETURN_MASTER](
	[SRM_ID] [int] IDENTITY(1,1) NOT NULL,
	[INVOICE_NO] [varchar](100) NULL,
	[DATE] [datetime] NULL,
	[CUSTOMER_ID] [int] NULL,
	[VEHICLE_NO] [varchar](100) NULL,
	[DESCRIPTION] [text] NULL,
	[MUAND_RATE] [float] NULL,
	[TOTAL_CANOLA] [float] NULL,
	[TOTAL_RDB] [float] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[SRM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SO_MATERIAL_P_DETAIL]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SO_MATERIAL_P_DETAIL](
	[MPD_ID] [int] IDENTITY(1,1) NOT NULL,
	[MPM_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[RATE] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[MPD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SO_MATERIAL_P_MASTER]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SO_MATERIAL_P_MASTER](
	[MPM_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATE] [datetime] NULL,
	[CUSTOMER_ID] [int] NULL,
	[INVOICE_NO] [varchar](50) NULL,
	[DESCRIPTION] [text] NULL,
	[CREDIT_DAYS] [int] NULL,
	[TOTAL] [float] NULL,
	[TOTAL_WEIGHT] [float] NULL,
	[REMAINING_WEIGHT] [float] NULL,
	[COMPANY_ID] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[SALE_TYPE] [char](1) NULL,
	[STATUS] [char](1) NULL,
	[MUAND_RATE] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[MPM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUPPLIER_PROFILE]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUPPLIER_PROFILE](
	[SUPP_PRO] [int] IDENTITY(1,1) NOT NULL,
	[COA_ID] [int] NULL,
	[SUPP_TYPE_ID] [int] NULL,
	[CONTACT_PERSON] [varchar](max) NULL,
	[MOBILE] [varchar](max) NULL,
	[EMAIL] [varchar](max) NULL,
	[ADDRESS] [varchar](max) NULL,
	[CITY_ID] [int] NULL,
	[NTN_NUMBER] [varchar](max) NULL,
	[STRN_NUMBER] [varchar](max) NULL,
	[GST_NUMBER] [varchar](max) NULL,
	[CREDIT_LIMIT] [float] NULL,
	[AREA_ID] [int] NULL,
	[STAT] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[SUPP_PRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUPPLIER_TYPES]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUPPLIER_TYPES](
	[SUPP_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](max) NULL,
	[STAT] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[SUPP_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAXES]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAXES](
	[TAX_ID] [int] IDENTITY(1,1) NOT NULL,
	[COA_ID] [int] NULL,
	[TAX_VALUE] [float] NULL,
	[TAX_TYPE] [int] NULL,
	[STAT] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[TAX_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblTEMP1]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblTEMP1](
	[DATE] [datetime] NULL,
	[INVOICE_NO] [varchar](50) NULL,
	[COA_NAME] [varchar](100) NULL,
	[AMOUNT] [decimal](18, 0) NULL,
	[DAYS] [int] NULL,
	[COA_ID] [int] NULL,
	[SALES_PERSON] [varchar](100) NULL,
	[REGION] [varchar](100) NULL,
	[DUE_DATE] [datetime] NULL,
	[LEDGER] [float] NULL,
	[CHQINHAND] [float] NULL,
	[ONLINE] [float] NULL,
	[AREA] [varchar](100) NULL,
	[area_id] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblTEMP2]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblTEMP2](
	[SALES_PERSON] [varchar](100) NULL,
	[1-19] [float] NULL,
	[20-30] [float] NULL,
	[31 above] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblTEMP3]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblTEMP3](
	[PROVINCE] [varchar](100) NULL,
	[1-19] [float] NULL,
	[20-30] [float] NULL,
	[31 above] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblTEMP4]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblTEMP4](
	[PROVINCE] [varchar](100) NULL,
	[SALES_PERSON] [varchar](100) NULL,
	[1-19] [float] NULL,
	[20-30] [float] NULL,
	[31 above] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblTEMP5]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblTEMP5](
	[SALES_PERSON] [varchar](100) NULL,
	[BALOCHISTAN] [float] NULL,
	[KPK] [float] NULL,
	[PUNJAB] [float] NULL,
	[SINDH] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblTEMPS1]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblTEMPS1](
	[DATE] [datetime] NULL,
	[INVOICE_NO] [varchar](50) NULL,
	[COA_NAME] [varchar](100) NULL,
	[VEHICLE_NO] [varchar](100) NULL,
	[MATERIAL] [varchar](100) NULL,
	[WEIGHT] [float] NULL,
	[RATE] [float] NULL,
	[AMOUNT] [float] NULL,
	[DAYS] [int] NULL,
	[COA_ID] [int] NULL,
	[DUE_DATE] [datetime] NULL,
	[TOTAL_DAYS] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblTEMPS2]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblTEMPS2](
	[SUPPLIER] [varchar](100) NULL,
	[1-10] [float] NULL,
	[11-20] [float] NULL,
	[21 above] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[temp]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[temp](
	[DAATE] [datetime] NULL,
	[REC_ACCOUNT] [varchar](max) NULL,
	[SUB_ACCOUNT] [varchar](max) NULL,
	[AMOUNT] [float] NULL,
	[BANK] [varchar](max) NULL,
	[BR_CODE] [varchar](100) NULL,
	[INSTRUMENT] [varchar](100) NULL,
	[PAYMENT_ACCOUNT] [varchar](max) NULL,
	[REF_ACCOUNT] [varchar](max) NULL,
	[STATUS] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRANSFER_CHQ]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRANSFER_CHQ](
	[PT_ID] [int] NULL,
	[CHQ_ID] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UNITS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UNITS](
	[UNIT_ID] [int] IDENTITY(1,1) NOT NULL,
	[UNIT_NAME] [varchar](max) NULL,
	[STAT] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATION_DATE] [datetime] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UploadData_Brands]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UploadData_Brands](
	[Brands] [nvarchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UploadDataProducts]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UploadDataProducts](
	[ID] [float] NULL,
	[BRAND] [nvarchar](255) NULL,
	[PRODUCT CODE] [float] NULL,
	[PRODUCT NAME] [nvarchar](255) NULL,
	[OLD NET RATE] [float] NULL,
	[OLD LIST RATE] [float] NULL,
	[NEW NET RATE] [float] NULL,
	[NEW LIST RATE] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[USERS_ID] [int] IDENTITY(1,1) NOT NULL,
	[USERS_NAME] [varchar](max) NULL,
	[PASS] [varchar](max) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[RIGHTS] [text] NULL,
	[COMPANY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[USERS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VEHICLES]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VEHICLES](
	[VEH_ID] [int] IDENTITY(1,1) NOT NULL,
	[VEH_NUMBER] [varchar](100) NULL,
	[CREATION_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFICATION_DATE] [datetime] NULL,
	[MODIFIED_BY] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTION_DETAIL]  WITH CHECK ADD FOREIGN KEY([PRODUCTION_MASTER_ID])
REFERENCES [dbo].[PRODUCTION_MASTER] ([ID])
GO
/****** Object:  StoredProcedure [dbo].[CREATE_BACKUP]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
create PROCEDURE [dbo].[CREATE_BACKUP]
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	declare @path varchar(500) = 'F:\Software BackUp Files\Stove2023_24_BackUp-'+Convert(varchar(100),YEAR(getdate()))+'-'+Convert(varchar(100),MONTH(getdate()))+'-'+Convert(varchar(100),DAY(getdate()))+'-'+FORMAT(getdate(),'hh-mm-ss')+'.bak';
	BACKUP DATABASE [BROKER_MANAGEMENT_SYSTEM_2023_24] TO DISK = @path;	
END
GO
/****** Object:  StoredProcedure [dbo].[CREATE_BACKUP_MAAZ_OIL_D]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CREATE_BACKUP_MAAZ_OIL_D]
	
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @PATH VARCHAR(MAX);
	SET @PATH = (SELECT 'D:\Software Files\BackUp Files-'+
	convert(varchar(50),DATEPART(YEAR,GETDATE()))+'-'+convert(varchar(50),DATEPART(MONTH,GETDATE()))+'-'+
	convert(varchar(50),DATEPART(DAY,GETDATE()))+'-'+convert(varchar(50),DATEPART(HOUR,GETDATE()))+'.bak');
	BACKUP DATABASE [MAAZ_OIL_D] TO DISK= @PATH;
END



GO
/****** Object:  StoredProcedure [dbo].[GET_CLOSING_INVENTORY]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GET_CLOSING_INVENTORY] 
	@REPORT_DATE DATETIME
AS
BEGIN
	SET NOCOUNT ON;
CREATE TABLE #TEMP_CLOSING_MATERIAL(
[DATE] DATETIME,
INVOICE_NO VARCHAR(100),
MATERIAL_ID INT,
MATERIAL_NAME VARCHAR(100),
NET_WEIGHT FLOAT,
KG_RATE FLOAT,
MUAND_RATE FLOAT--,
--AMOUNT FLOAT
)

DECLARE db_cursor CURSOR FOR 
SELECT '01-07-2020' AS [DATE],'OPENING' AS [INVOICE_NO],MATERIAL_ID,MATERIAL_NAME,
OPENING_QTY AS [NET_WEIGHT],OPENING_RATE AS [KG_RATE],ROUND(OPENING_RATE * 37.324,4) AS [MUAND RATE],'0' AS [PI_ID]
FROM MATERIALS
UNION ALL
SELECT A.[DATE],A.INVOICE_NO,B.MATERIAL_ID,C.MATERIAL_NAME,A.NET_WEIGHT,A.KG_RATE,A.MUAND_RATE,A.PI_ID
FROM PURCHASES A
INNER JOIN PURCHASES_ORDER B ON A.PO_ID = B.PO_ID
INNER JOIN MATERIALS C ON B.MATERIAL_ID = C.MATERIAL_ID
WHERE A.PI_ID NOT IN (SELECT purchases_id FROM purchases_sales_transfer) AND A.[DATE] <= @REPORT_DATE
ORDER BY MATERIAL_ID,[DATE],PI_ID

DECLARE @DATE DATETIME;
DECLARE @INVOICE VARCHAR(100);
DECLARE @MATERIAL_ID INT;
DECLARE @MATERIAL_NAME VARCHAR(100);
DECLARE @NET_WEIGHT FLOAT;
DECLARE @KG_RATE FLOAT;
DECLARE @MUAND_RATE FLOAT;
DECLARE @PI_ID INT;
	
DECLARE @PRE_MATERIAL_ID INT = 0;
DECLARE @SALES FLOAT = 0;
DECLARE @SALES_RETURN FLOAT = 0;
DECLARE @ADJUSTMENT FLOAT = 0;
DECLARE @AA_SALES FLOAT = 0;
DECLARE @SOLD_WEIGHT FLOAT = 0;

OPEN db_cursor;

FETCH NEXT FROM db_cursor INTO @DATE,@INVOICE,@MATERIAL_ID,@MATERIAL_NAME,@NET_WEIGHT,@KG_RATE,@MUAND_RATE,@PI_ID;
	WHILE @@FETCH_STATUS = 0  
	BEGIN  
		IF(@MATERIAL_ID <> @PRE_MATERIAL_ID)
		BEGIN
			SET @PRE_MATERIAL_ID = @MATERIAL_ID;
			SET @SALES = (SELECT
				--SALES DIRECT ORDER
				(SELECT SUM(C.WEIGHT) AS [TOTAL_WEIGHT]
				FROM SALES A
				INNER JOIN SALES_PROGRAM_MASTER B ON A.SOP_ID = B.SPM_ID
				INNER JOIN SALES_PROGRAM_DETAILS C ON B.SPM_ID = C.SPM_ID
				INNER JOIN MATERIALS E ON C.PRODUCT_ID = E.MATERIAL_ID
				WHERE E.MATERIAL_ID = @MATERIAL_ID AND A.[DATE] <= @REPORT_DATE
				GROUP BY E.MATERIAL_ID,E.MATERIAL_NAME)
				+
				--SALES PRODUCT ORDER
				(SELECT SUM(C.WEIGHT) AS [TOTAL_WEIGHT]
				FROM SALES A
				INNER JOIN SALES_PROGRAM_MASTER B ON A.SOP_ID = B.SPM_ID 
				INNER JOIN SALES_PROGRAM_DETAILS C ON B.SPM_ID = C.SPM_ID
				INNER JOIN PRODUCT_MASTER E ON C.PRODUCT_ID = E.PM_ID
				INNER JOIN PRODUCT_DETAILS G ON E.PM_ID = G.PM_ID
				INNER JOIN MATERIALS X ON G.MATERIAL_ID = X.MATERIAL_ID
				WHERE X.MATERIAL_ID = @MATERIAL_ID AND A.[DATE] <= @REPORT_DATE
				GROUP BY X.MATERIAL_ID,X.MATERIAL_NAME)
			);

			SET @ADJUSTMENT = (
				--INVENTORY ADJUSTMENT
				SELECT 
				SUM(CASE WHEN A.ADD_LESS = 'A' THEN A.QTY ELSE -A.QTY END) AS [TOTAL_WEIGHT]  
				FROM INVENTORY_ADJUSTMENTS A
				INNER JOIN MATERIALS B ON A.MATERIAL_ID = B.MATERIAL_ID
				WHERE B.MATERIAL_ID = @MATERIAL_ID AND A.[DATE] <= @REPORT_DATE
				GROUP BY B.MATERIAL_ID,B.MATERIAL_NAME
			);

			SET @SALES_RETURN = (
				--SALES RETURN
				SELECT SUM(B.ITEM_WEIGHT) AS [TOTAL_WEIGHT] 
				FROM SALES_RETURN_MASTER A
				INNER JOIN SALES_RETURN_DETAIL B ON A.SRM_ID = B.SRM_ID
				INNER JOIN MATERIALS C ON B.MATERIAL_ID = C.MATERIAL_ID
				WHERE B.MATERIAL_ID = @MATERIAL_ID AND A.[DATE] <= @REPORT_DATE
				GROUP BY B.MATERIAL_ID,C.MATERIAL_NAME
			);

			SET @AA_SALES = (
				--SALES AA
				SELECT SUM(A.sales_weight) AS [TOTAL_WEIGHT]
				FROM AA_SALES A
				INNER JOIN SALES_ORDER_DIRECT B ON A.so_id = B.SOD_ID
				INNER JOIN MATERIALS E ON B.MATERIAL_ID = E.MATERIAL_ID
				WHERE E.MATERIAL_ID = @MATERIAL_ID AND A.[DATE] <= @REPORT_DATE
				GROUP BY E.MATERIAL_ID,E.MATERIAL_NAME 
			);

			SET @SOLD_WEIGHT = ISNULL(@SALES,0) - ISNULL(@SALES_RETURN,0) - ISNULL(@ADJUSTMENT,0) + ISNULL(@AA_SALES,0);

			IF(@SOLD_WEIGHT >= @NET_WEIGHT)
			BEGIN
				SET @SOLD_WEIGHT = @SOLD_WEIGHT - @NET_WEIGHT
			END
			ELSE
			BEGIN
					INSERT INTO #TEMP_CLOSING_MATERIAL ([DATE],INVOICE_NO,MATERIAL_ID,MATERIAL_NAME,NET_WEIGHT,KG_RATE,MUAND_RATE) 
					VALUES (@DATE,@INVOICE,@MATERIAL_ID,@MATERIAL_NAME,ROUND(@NET_WEIGHT - @SOLD_WEIGHT,2),@KG_RATE,@MUAND_RATE);
				--IF(@MATERIAL_ID = 5005)
				--BEGIN
				--	INSERT INTO #TEMP_CLOSING_MATERIAL ([DATE],INVOICE_NO,MATERIAL_ID,MATERIAL_NAME,NET_WEIGHT,KG_RATE,MUAND_RATE,AMOUNT) 
				--	VALUES (@DATE,@INVOICE,@MATERIAL_ID,@MATERIAL_NAME,ROUND(@NET_WEIGHT - @SOLD_WEIGHT,2),@KG_RATE,@MUAND_RATE,
				--	ROUND((@NET_WEIGHT* @KG_RATE),2));
				--END
				--ELSE
				--BEGIN
				--	INSERT INTO #TEMP_CLOSING_MATERIAL ([DATE],INVOICE_NO,MATERIAL_ID,MATERIAL_NAME,NET_WEIGHT,KG_RATE,MUAND_RATE,AMOUNT) 
				--	VALUES (@DATE,@INVOICE,@MATERIAL_ID,@MATERIAL_NAME,ROUND(@NET_WEIGHT - @SOLD_WEIGHT,2),@KG_RATE,@MUAND_RATE,
				--	ROUND((@NET_WEIGHT* (@MUAND_RATE / 37.324)),2));
				--END
				
				SET @SOLD_WEIGHT = 0;
				SET @SALES_RETURN = 0;
				SET @SALES = 0;
				SET @ADJUSTMENT = 0;
				SET @AA_SALES = 0;
			END
		END
		ELSE
		BEGIN
			IF(@SOLD_WEIGHT >= @NET_WEIGHT)
			BEGIN
				SET @SOLD_WEIGHT = @SOLD_WEIGHT - @NET_WEIGHT
			END
			ELSE
			BEGIN
					INSERT INTO #TEMP_CLOSING_MATERIAL ([DATE],INVOICE_NO,MATERIAL_ID,MATERIAL_NAME,NET_WEIGHT,KG_RATE,MUAND_RATE) 
					VALUES (@DATE,@INVOICE,@MATERIAL_ID,@MATERIAL_NAME,ROUND(@NET_WEIGHT - @SOLD_WEIGHT,2),@KG_RATE,@MUAND_RATE);
				--IF(@MATERIAL_ID = 5005)
				--BEGIN
				--	INSERT INTO #TEMP_CLOSING_MATERIAL ([DATE],INVOICE_NO,MATERIAL_ID,MATERIAL_NAME,NET_WEIGHT,KG_RATE,MUAND_RATE,AMOUNT) 
				--	VALUES (@DATE,@INVOICE,@MATERIAL_ID,@MATERIAL_NAME,ROUND(@NET_WEIGHT - @SOLD_WEIGHT,2),@KG_RATE,@MUAND_RATE,
				--	ROUND((@NET_WEIGHT* @KG_RATE),2));
				--END
				--ELSE
				--BEGIN
				--	INSERT INTO #TEMP_CLOSING_MATERIAL ([DATE],INVOICE_NO,MATERIAL_ID,MATERIAL_NAME,NET_WEIGHT,KG_RATE,MUAND_RATE,AMOUNT) 
				--	VALUES (@DATE,@INVOICE,@MATERIAL_ID,@MATERIAL_NAME,ROUND(@NET_WEIGHT - @SOLD_WEIGHT,2),@KG_RATE,@MUAND_RATE,
				--	ROUND((@NET_WEIGHT* (@MUAND_RATE / 37.324)),2));
				--END
				SET @SOLD_WEIGHT = 0;
				SET @SALES_RETURN = 0;
				SET @SALES = 0;
				SET @ADJUSTMENT = 0;
				SET @AA_SALES = 0;
			END
		END
	FETCH NEXT FROM db_cursor INTO @DATE,@INVOICE,@MATERIAL_ID,@MATERIAL_NAME,@NET_WEIGHT,@KG_RATE,@MUAND_RATE,@PI_ID;
	END;
CLOSE db_cursor;
DEALLOCATE db_cursor;
--SELECT * FROM #TEMP_CLOSING_MATERIAL;
SELECT [DATE],INVOICE_NO,MATERIAL_ID,MATERIAL_NAME,NET_WEIGHT,KG_RATE,MUAND_RATE,
ROUND((NET_WEIGHT* 
	(CASE WHEN MATERIAL_ID = 5005 THEN KG_RATE ELSE ROUND((MUAND_RATE / 37.324),8) END))
,2) AS AMOUNT
FROM #TEMP_CLOSING_MATERIAL
ORDER BY [DATE] DESC;
DROP TABLE #TEMP_CLOSING_MATERIAL;
END



GO
/****** Object:  StoredProcedure [dbo].[GET_MATERIAL_CALCULATION]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GET_MATERIAL_CALCULATION] 
	@DATE DATETIME
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE db_cursor CURSOR FOR 

	SELECT A.PRODUCT_ID,A.QTY,'P' AS [TYPE],A.GPM_ID
	FROM GATE_PASS_DETAILS A
	WHERE A.GPM_ID NOT IN (SELECT GP_ID FROM SALES_MASTER) AND A.ITEM_TYPE = 'P'
	UNION ALL
	SELECT A.PRODUCT_ID AS [RAW_ID],A.QTY,'R' AS [TYPE],A.GPM_ID
	FROM GATE_PASS_DETAILS A
	WHERE A.GPM_ID NOT IN (SELECT GP_ID FROM SALES_MASTER) AND A.ITEM_TYPE = 'R'

	DECLARE @ITEM_ID INT;
	DECLARE @QTY FLOAT;
	DECLARE @TYPE CHAR;
	DECLARE @REF_ID INT;

	OPEN db_cursor;

	FETCH NEXT FROM db_cursor INTO @ITEM_ID,@QTY,@TYPE,@REF_ID;
		WHILE @@FETCH_STATUS = 0  
		BEGIN  
			IF(@TYPE = 'P')
			BEGIN
				INSERT INTO MATERIAL_ITEM_LEDGER 
				SELECT @DATE,B.MATERIAL_ID,@REF_ID,'GATE PASS',0,(WEIGHT * @QTY),0,0,1,1,GETDATE(),NULL,NULL,1
				FROM PRODUCT_MASTER A
				INNER JOIN PRODUCT_DETAILS B ON A.PM_ID = B.PM_ID
				WHERE A.PM_ID = @ITEM_ID

				INSERT INTO PRODUCT_ITEM_LEDGER (DATE,PRODUCT_ID,REF_NO,ENTRY_FROM,STOCK_IN,STOCK_OUT,COST_AMT,SALE_AMT,L_ID,CREATED_BY,CREATION_DATE,COMPANY_ID)
				VALUES (@DATE,@ITEM_ID,@REF_ID,'GATE PASS',@QTY,0,0,0,1,1,GETDATE(),1)
				
			END
			ELSE 
			BEGIN
				INSERT INTO MATERIAL_ITEM_LEDGER 
				SELECT @DATE,@ITEM_ID,@REF_ID,'GATE PASS',0,@QTY,0,0,1,1,GETDATE(),NULL,NULL,1
			END
		FETCH NEXT FROM db_cursor INTO @ITEM_ID,@QTY,@TYPE,@REF_ID
		END;
	CLOSE db_cursor;
	DEALLOCATE db_cursor;

END




GO
/****** Object:  StoredProcedure [dbo].[GETPRODUCTLIST]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[GETPRODUCTLIST](
	@NAME VARCHAR(MAX),
	@BRAND_ID INT
)                                   
AS
  BEGIN
      SET TRANSACTION ISOLATION LEVEL SNAPSHOT
      SET NOCOUNT ON;

      SELECT PM_ID AS ID,PRODUCT_NAME AS [NAME] 
	  FROM PRODUCT_MASTER
      WHERE  (@NAME IS NULL OR PRODUCT_NAME+'-'+PRODUCT_CODE LIKE '%' + @NAME + '%') AND BRAND_ID = @BRAND_ID
	  ORDER BY ID					  
  END
GO
/****** Object:  StoredProcedure [dbo].[UPDATE_PRODUCTION]    Script Date: 11/06/2024 1:44:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UPDATE_PRODUCTION] 
	@PROGRAM_ID INT
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE db_cursor CURSOR FOR 
	
	SELECT A.PRODUCT_ID,A.QTY AS [PRODUCT_QTY],A.RATE AS [PRODUCT_SALE_RATE],ITEM_TYPE,B.DATE AS [SALE_DATE],
	B.S_ID AS [SALE_ID]
	FROM SALES_PROGRAM_DETAILS A
	INNER JOIN SALES B ON A.SPM_ID = B.SOP_ID
	WHERE A.SPM_ID = @PROGRAM_ID

	--SELECT A.PRODUCT_ID,A.QTY,'P' AS [TYPE],A.GPM_ID
	--FROM GATE_PASS_DETAILS A
	--WHERE A.GPM_ID NOT IN (SELECT GP_ID FROM SALES_MASTER) AND A.ITEM_TYPE = 'P'
	--UNION ALL
	--SELECT A.PRODUCT_ID AS [RAW_ID],A.QTY,'R' AS [TYPE],A.GPM_ID
	--FROM GATE_PASS_DETAILS A
	--WHERE A.GPM_ID NOT IN (SELECT GP_ID FROM SALES_MASTER) AND A.ITEM_TYPE = 'R'

	DECLARE @ITEM_ID INT;
	DECLARE @QTY FLOAT;
	DECLARE @RATE FLOAT;
	DECLARE @TYPE CHAR;
	DECLARE @SALE_DATE DATETIME;
	DECLARE @SALE_ID INT;
	
	OPEN db_cursor;
	FETCH NEXT FROM db_cursor INTO @ITEM_ID,@QTY,@RATE,@TYPE,@SALE_DATE,@SALE_ID;
		WHILE @@FETCH_STATUS = 0  
		BEGIN  
			IF(@TYPE = 'P')
			BEGIN
				INSERT INTO MATERIAL_ITEM_LEDGER 
				SELECT @SALE_DATE,B.MATERIAL_ID,@SALE_ID,'SALES',0,(B.[WEIGHT] * @QTY),0,0,1,1,GETDATE(),NULL,NULL,1
				FROM PRODUCT_MASTER A
				INNER JOIN PRODUCT_DETAILS B ON A.PM_ID = B.PM_ID
				WHERE A.PM_ID = @ITEM_ID
				SELECT * FROM PRODUCT_ITEM_LEDGER
				INSERT INTO PRODUCT_ITEM_LEDGER (DATE,PRODUCT_ID,REF_NO,ENTRY_FROM,STOCK_IN,STOCK_OUT,COST_AMT,SALE_AMT,L_ID,CREATED_BY,CREATION_DATE,COMPANY_ID)
				VALUES (@SALE_DATE,@ITEM_ID,@SALE_ID,'SALES',@QTY,@QTY,0,@RATE,1,1,GETDATE(),1)
				
			END
			ELSE 
			BEGIN
				INSERT INTO MATERIAL_ITEM_LEDGER 
				SELECT @SALE_DATE,@ITEM_ID,@SALE_ID,'SALES',0,@QTY,0,@RATE,1,1,GETDATE(),NULL,NULL,1
			END
		FETCH NEXT FROM db_cursor INTO @ITEM_ID,@QTY,@RATE,@TYPE,@SALE_DATE,@SALE_ID
		END;
	CLOSE db_cursor;
	DEALLOCATE db_cursor;

END

drop database [BROKER_MANAGEMENT_SYSTEM_2023_24]


GO
USE [master]
GO
ALTER DATABASE [BROKER_MANAGEMENT_SYSTEM_2023_24] SET  READ_WRITE 
GO
