SELECT* FROM SALE_MASTER

SELECT A.SALE_MASTER_ID AS [ID],A.INVOICE_NO AS [INVOICE #],
            A.[DATE],B.COA_NAME AS [CUSTOMER],A.[DESCRIPTION],
         A.CUSTOMER_ID
            FROM SALE_MASTER A
            INNER JOIN COA B ON A.CUSTOMER_ID = B.COA_ID
            ORDER BY SALE_MASTER_ID DESC



//for making quotation

SELECT * INTO QUOTATION_MASTER
FROM SALE_MASTER
WHERE 1 = 0;


SELECT * from QUOTATION_MASTER




ALTER TABLE QUOTATION_MASTER
DROP COLUMN CREDIT_DAYS;

ALTER TABLE QUOTATION_MASTER
DROP COLUMN ITEM_TYPE;



EXEC sp_rename 'QUOTATION_MASTER.SALE_MASTER_ID', 'QUOTATION_MASTER_ID', 'COLUMN';

SELECT A.QUOTATION_MASTER_ID AS [ID],A.INVOICE_NO AS [INVOICE #],
            A.[DATE],B.COA_NAME AS [CUSTOMER],A.[DESCRIPTION],
            A.CUSTOMER_ID
            FROM QUOTATION_MASTER A
            INNER JOIN COA B ON A.CUSTOMER_ID = B.COA_ID
            ORDER BY QUOTATION_MASTER_ID DESC




SELECT MAX(QUOTATION_MASTER_ID) FROM QUOTATION_MASTER


SELECT* FROM SALE_DETAIL


SELECT * INTO QUOTATION_DETAIL
FROM SALE_DETAIL
WHERE 1 = 0;




SELECT * FROM QUOTATION_DETAIL


EXEC sp_rename 'QUOTATION_DETAIL.SALE_DETAIL', 'QUOTATION_DETAIL', 'COLUMN';

// Purchase_Order


SELECT* FROM PURCHASES_ORDER
SELECT* FROM PURCHASES_DETAILS


SELECT A.SUPPLIER_ID,D.COA_NAME AS [SUPPLIER],
            B.M_TYPE_ID,C.M_TYPE_NAME AS [MATERIAL TYPE],A.MATERIAL_ID,B.MATERIAL_NAME AS [MATERIAL],
            A.WEIGHT,E.UNIT_NAME AS [UNIT],A.KG_RATE AS [KG RATE],A.MUAND_RATE AS [MUAND RATE],
            A.MUAND_VALUE AS[MUAND_VALUE],(A.KG_RATE * A.WEIGHT) AS [TOTAL], A.DESCRIPTION,A.CREDIT_DAYS,A.[STATUS]
            FROM PURCHASES_ORDER A,MATERIALS B,MATERIAL_TYPES C,COA D,UNITS E
            WHERE A.MATERIAL_ID = B.MATERIAL_ID AND B.M_TYPE_ID = C.M_TYPE_ID 
            AND A.SUPPLIER_ID = D.COA_ID AND B.UNIT_ID = E.UNIT_ID
            ORDER BY A.DATE DESC



			 SELECT A.PURCHASE_MASTER_ID AS[ID], A.INVOICE_NO AS[INVOICE #],
               A.[DATE], B.COA_NAME AS[SUPPLIER], A.[DESCRIPTION],
                           A.SUPPLIER_ID
            
                           FROM PURCHASE_MASTER A
            
                           INNER JOIN COA B ON A.SUPPLIER_ID = B.COA_ID
            
                           ORDER BY PURCHASE_MASTER_ID DESC

SELECT* FROM PURCHASE_RETURN



SELECT * INTO PURCHASE_ORDER
FROM PURCHASE_RETURN
WHERE 1 = 0;


SELECT*FROM PURCHASE_ORDER



SELECT A.PURCHASE_MASTER_ID AS[ID], A.INVOICE_NO AS[INVOICE #],
               A.[DATE], B.COA_NAME AS[SUPPLIER], A.[DESCRIPTION],
                            A.SUPPLIER_ID
            
                           FROM PURCHASE_ORDER A
            
                           INNER JOIN COA B ON A.SUPPLIER_ID = B.COA_ID
            
            
			               ORDER BY PURCHASE_MASTER_ID DESC



						   SELECT MAX(PURCHASE_MASTER_ID) FROM PURCHASE_ORDER

						   SELECT* FROM PURCHASES_DETAILS
						   SELECT* FROM PURCHASE_DETAIL

						   SELECT* FROM PRODUCT_MASTER

						   SELECT* FROM PURCHASE_ORDER
						   SELECT* FROM PURCHASES_ORDER
						   SELECT* FROM PURCHASE_RETURN
	

	SELECT * FROM LEDGERS
						   SELECT A.MATERIAL_ID, B.PRODUCT_NAME AS [PRODUCT], A.QTY, A.RATE, (A.QTY*A.RATE) AS [TOTAL]
                  FROM PURCHASES_DETAILS A
                  INNER JOIN PRODUCT_MASTER B ON A.MATERIAL_ID = B.PM_ID
                  WHERE A.PURCHASE_MASTER_ID =1











SELECT* FROM PURCHASE_ORDER

ALTER TABLE PURCHASE_ORDER
DROP COLUMN ITEM_TYPE ;



















// NOW TESTING PURCHASE 
SELECT A.PURCHASE_MASTER_ID AS[ID], A.INVOICE_NO AS[INVOICE #],
               A.[DATE], B.COA_NAME AS[SUPPLIER], A.[DESCRIPTION],
                           A.CREDIT_DAYS, A.SUPPLIER_ID
            
                           FROM PURCHASE_MASTER A
            
                           INNER JOIN COA B ON A.SUPPLIER_ID = B.COA_ID
            
                           ORDER BY PURCHASE_MASTER_ID DESC


						   SELECT * FROM PURCHASE_MASTER


//NOW TESTING PURCHASE RETURN

SELECT* FROM PURCHASE_RETURN

ALTER TABLE PURCHASE_RETURN
DROP COLUMN ITEM_TYPE;



//TESING QUOTATION 
SELECT* FROM QUOTATION_MASTER

SELECT 
    A.ITEM_ID, 
    B.MATERIAL_NAME AS [ITEM NAME], 
    A.QTY, 
    A.RATE, 
    (A.QTY * A.RATE) AS [TOTAL], 
    '' AS [CODE]
FROM 
    QUOTATION_DETAIL A
INNER JOIN 
    MATERIALS B ON A.ITEM_ID = B.MATERIAL_ID
WHERE 
    A.QUOTATION_MASTER_ID = 22

UNION ALL

SELECT 
    A.ITEM_ID, 
    B.PRODUCT_NAME AS [ITEM NAME], 
    A.QTY, 
    A.RATE, 
    (A.QTY * A.RATE) AS [TOTAL], 
    B.PRODUCT_CODE AS [CODE]
FROM 
    QUOTATION_DETAIL A
INNER JOIN 
    PRODUCT_MASTER B ON A.ITEM_ID = B.PM_ID
WHERE 
    A.QUOTATION_MASTER_ID = 22

	select* from QUOTATION_DETAIL 

	SELECT A.MATERIAL_ID, B.PRODUCT_NAME AS [PRODUCT], A.QTY, A.RATE, (A.QTY*A.RATE) AS [TOTAL]
                  FROM PURCHASE_DETAIL A
                  INNER JOIN PRODUCT_MASTER B ON A.MATERIAL_ID = B.PM_ID
                  WHERE A.PURCHASE_MASTER_ID = 12


				  SELECT A.ITEM_ID, B.MATERIAL_NAME AS [ITEM NAME], A.QTY, A.RATE, (A.QTY*A.RATE) AS [TOTAL], '' AS [CODE]
               FROM QUOTATION_DETAIL A
                INNER JOIN MATERIALS B ON A.ITEM_ID = B.MATERIAL_ID
                WHERE A.QUOTATION_MASTER_ID = 5
                UNION ALL
                SELECT A.ITEM_ID, B.PRODUCT_NAME AS [ITEM NAME], A.QTY, A.RATE, (A.QTY*A.RATE) AS [TOTAL], B.PRODUCT_CODE AS [CODE]
                FROM QUOTATION_DETAIL A
               INNER JOIN PRODUCT_MASTER B ON A.ITEM_ID = B.PM_ID
                WHERE A.QUOTATION_MASTER_ID = 5
  

  SELECT* FROM PRODUCT_MASTER 
  SELECT* FROM QUOTATION_DETAIL
  SELECT* FROM SALE_DETAIL

  SELECT* FROM QUOTATION_MASTER
  SELECT* FROM SALE_DETAIL
  SELECT A.ITEM_ID, B.MATERIAL_NAME AS [ITEM NAME], A.QTY, A.RATE, (A.QTY*A.RATE) AS [TOTAL]
               FROM QUOTATION_DETAIL A
                INNER JOIN MATERIALS B ON A.ITEM_ID = B.MATERIAL_ID
                WHERE A.QUOTATION_MASTER_ID = 5
                UNION ALL
                SELECT A.ITEM_ID, B.PRODUCT_NAME AS [ITEM NAME], A.QTY, A.RATE, (A.QTY*A.RATE) AS [TOTAL]
                FROM QUOTATION_DETAIL A
               INNER JOIN PRODUCT_MASTER B ON A.ITEM_ID = B.PM_ID
                WHERE A.QUOTATION_MASTER_ID = 5

 SELECT 'QO-' + 
       CONVERT(varchar(100), (ISNULL(COUNT(QUOTATION_MASTER_ID), 0) + 1)) + '-' + 
       CONVERT(varchar(100), YEAR(GETDATE())) + '/' + 
       CONVERT(varchar(100), (ISNULL(MAX(QUOTATION_MASTER_ID), 0) + 1))
FROM QUOTATION_MASTER;

SELECT 'QI-' + CONVERT(varchar(100), (ISNULL(COUNT(QUOTATION_MASTER_ID), 0) + 1)) + 
                     '-' + CONVERT(varchar(100), YEAR(GETDATE())) + '/' + 
                     CONVERT(varchar(100), (ISNULL(MAX(QUOTATION_MASTER_ID), 0) + 1))
                     FROM QUOTATION_MASTER