SELECT* FROM SALE_MASTER
SELECT* FROM LEDGERS

SELECT* FROM  SALES_ORDER_PRODUCT_DETAILS 

ALTER TABLE SALE_DETAIL 
ADD GST DECIMAL(5, 2);


SELECT A.ITEM_ID, A.QTY, A.RATE, A.GST
FROM SALE_DETAIL A
WHERE A.SALE_MASTER_ID = 1;

SELECT A.ITEM_ID, 
       B.PRODUCT_NAME AS [PRODUCT], 
       A.QTY, 
       A.RATE, 
       (A.QTY * A.RATE) AS [TOTAL], 
       (A.QTY * A.RATE) * (ISNULL(A.GST, 0) / 100) AS [TOTAL_WITH_GST]  -- Correct formula
FROM SALE_DETAIL A
INNER JOIN PRODUCT_MASTER B ON A.ITEM_ID = B.PM_ID
WHERE A.SALE_MASTER_ID = 1;
