select * from coa
SELECT* FROM LEDGERS

ALTER TABLE LEDGER
ADD BANK_ID INT NULL;


SELECT* FROM CASH_VOUCHER

DELETE FROM LEDGERS WHERE REF_ID = '101' AND ENTRY_OF = 'CASH RECEIPT';

select* from CASH_PAY_VOUCHER

SELECT * INTO BANK_VOUCHER
FROM CASH_VOUCHER;

SELECT * FROM BANK_VOUCHER
SELECT* FROM BANK_PAY_VOUCHER
SELECT* FROM CASH_PAY_VOUCHER

SELECT '0' AS [id],'--SELECT BANK--' AS [name]
                UNION ALL
                SELECT COA_ID AS [ID],COA_NAME AS [NAME] 
                FROM COA WHERE STAT = 0";


SELECT* FROM LEDGERS

SELECT* FROM  CASH_VOUCHER
SELECT* FROM BANK_VOUCHER
SELECT ID FROM CASH_VOUCHER WHERE ID =42
SELECT * FROM CASH_PAY_VOUCHER


SELECT ID AS[ID], A.DATE ,
                       A.AMOUNT, A.DESCRIPTION, C.COA_NAME AS [ACCOUNT]
                       FROM  CASH_VOUCHER A 
                       INNER JOIN COA C ON A.ACCOUNT_ID = C.COA_ID
                       WHERE A.ACCOUNT_ID = 2106


					   SELECT B.COA_NAME AS [PAYMENT ACCOUNT], SUM(A.AMOUNT) AS TOTAL
FROM BANK_VOUCHER A
INNER JOIN COA B ON A.ACCOUNT_ID = B.COA_ID
WHERE A.[DATE] BETWEEN '2024-11-01 00:00:00' AND '2024-11-01 23:59:59'
AND A.VOUCHER_TYPE = 'P'
GROUP BY B.COA_NAME;








