SELECT*  FROM CASH_PAY_VOUCHER 
SELECT * FROM CASH_REC_VOUCHER          


SELECT * INTO CASH_PAYMENT FROM CASH_PAY_VOUCHER  WHERE 1 = 0


SELECT * INTO CASH_RECEIPT FROM CASH_REC_VOUCHER     WHERE 1 = 0



SELECT * FROM CASH_PAY_VOUCHER
SELECT* FROM CASHPAYRECMASTER

ALTER TABLE CASH_RECEIPT
DROP COLUMN REF_ACCOUNT;
SELECT* FROM CASHBANKRECMASTER

SELECT* FROM Coa


SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CASH_PAYMENT' 

CASHBANKRECMASTER


// DROPING COL 
SELECT* FROM CASH_PAYMENT
ALTER TABLE CASH_PAYMENT 
DROP COLUMN PAID_TO;

ALTER TABLE CASH_PAYMENT 
DROP COLUMN REF_ACCOUNT;

EXEC sp_rename 'CASH_PAYMENT.ACCOUNT_OF', 'DESCRIPTION', 'COLUMN';

 
SELECT*  FROM CASHPAYRECMASTER

ALTER TABLE CASHPAYRECMASTER
ADD TYPE CHAR(1);





SELECT* FROM CASHPAYRECMASTER





SELECT DISTINCT 
    A.CPV_ID,
    A.CPV_CODE AS [VOUCHER #],
    CONVERT(varchar(MAX), A.DAATE) AS [DATE],
    B.COA_NAME AS [ACCOUNT],
    A.COA_ID,
    '0' AS [RECEIVED AMOUNT],
    LTRIM(STR(A.AMOUNT, 25, 2)) AS [PAYMENT AMOUNT],
    A.REF_ACCOUNT AS [REF ACCOUNT],
    A.PAID_TO AS [PAID TO],
    '-' AS [RECV PERSON],
    A.TRANS_CODE,
    A.ACCOUNT_OF AS [NARRATION]
FROM CASH_PAY_VOUCHER A
JOIN COA B ON A.COA_ID = B.COA_ID
JOIN COA C ON A.COA_ID = C.COA_ID
WHERE A.DAATE BETWEEN '2024-11-01 00:00:00' AND '2024-11-01 23:59:59'

UNION ALL

SELECT DISTINCT 
    A.CRV_ID,
    A.CRV_CODE AS [VOUCHER #],
    CONVERT(varchar(MAX), A.DAATE) AS [DATE],
    B.COA_NAME AS [ACCOUNT],
    A.COA_ID,
    LTRIM(STR(A.AMOUNT, 25, 2)) AS [RECEIVED AMOUNT],
    '0' AS [PAYMENT AMOUNT],
    A.REF_ACCOUNT AS [REF ACCOUNT],
    '-' AS [PAID TO],
    R.REC_PERSON_NAME AS [RECV PERSON],
    A.TRANS_CODE,
    A.DESCRIPTION AS [NARRATION]
FROM CASH_REC_VOUCHER A
JOIN COA B ON A.COA_ID = B.COA_ID
JOIN COA C ON A.COA_ID = C.COA_ID
JOIN RECOVERY_PERSON R ON A.REC_PERSON_ID = R.REC_PERSON_ID
WHERE A.DAATE BETWEEN '2024-11-01 00:00:00' AND '2024-11-01 23:59:59'
ORDER BY [DATE] DESC;


SELECT DISTINCT 
  A.CPV_CODE AS [VOUCHER #],
  CONVERT(varchar(MAX), A.DAATE) AS [DATE],
  B.COA_NAME AS [ACCOUNT],
  A.COA_ID,
  A.TRANS_CODE,
  A.DESCRIPTION,
  A.AMOUNT,
  A.TYPE  -- Removed the semicolon before FROM
FROM CASHPAYRECMASTER A
INNER JOIN COA B ON A.COA_ID = B.COA_ID
WHERE A.DAATE BETWEEN '2024-11-01 00:00:00' AND '2024-11-01 23:59:59'
ORDER BY [DATE] DESC;


SELECT* FROM CASHPAYRECMASTER


SELECT* FROM CASHPAYRECMASTER 


SELECT CPV_ID AS [ID],C.COA_NAME AS [DEBIT_TO],A.DAATE AS [DATE],
	        A.AMOUNT, A.DESCRIPTION
	        FROM  CASHPAYRECMASTER  A 
	        INNER JOIN COA C ON A.COA_ID = C.COA_ID
	        WHERE A.CPV_ID = 1






SELECT *
INTO CASHBANKRECMASTER
FROM CASHPAYRECMASTER
WHERE 1 = 0;

ALTER TABLE CASHBANKRECMASTER
ADD BANK_ID INT NULL;

select*from CASHBANKRECMASTER




ALTER TABLE LEDGERS
ADD BANK_ID INT NULL;

SELECT '0' AS [id],'--SELECT BANKACCOUNT--' AS [name]
            UNION ALL
            SELECT COA_ID,COA_NAME FROM COA;\


			SELECT* FROM COA
			EXEC sp_rename 'CASH_REC_VOUCHER.CPV_ID', 'CRV_ID', 'COLUMN';


			SELECT * FROM CASH_REC_VOUCHER FROM CASH_PAY_VOUCHER WHERE 1 = 0;



			DECLARE @StartDate DATETIME;
DECLARE @EndDate DATETIME;

SET @StartDate = '2024-11-01 00:00:00'; -- Yahan apna start date daalein
SET @EndDate = '2024-11-01 23:59:59'; -- Yahan apna end date daalein

SELECT B.COA_NAME AS [SALES PERSON], SUM(A.AMOUNT) AS TOTAL
FROM CASHPAYRECMASTER A
INNER JOIN COA B ON A.COA_ID = B.COA_ID
WHERE A.DAATE BETWEEN @StartDate AND @EndDate 
AND A.Type = '0'  -- assuming 'Type' column holds the type
GROUP BY B.COA_NAME;


//load_recipt_grid
SELECT B.COA_NAME AS[SALES PERSON], SUM(A.AMOUNT) AS TOTAL
            FROM CASHPAYRECMASTER A
            INNER JOIN COA B ON A.COA_ID = B.COA_ID
            WHERE A.DAATE BETWEEN '" + Classes.Helper.ConvertDatetime(date.Date)+ "' AND '" + Classes.Helper.ConvertDatetime(date.Date.AddHours(23).AddMinutes(59).AddSeconds(59))+ @"'
            AND A.Type = '1' 
            GROUP BY B.COA_NAME"

			SELECT* FROM CASHPAYRECMASTER
		
		
			SELECT* FROM	CASHBANKRECMASTER



			SELECT DISTINCT A.CPV_ID, A.BANK_ID, A.CPV_CODE AS [VOUCHER #],CONVERT(varchar(MAX), A.DAATE) AS [DATE], B.COA_NAME AS [ACCOUNT], A.COA_ID, A.TRANS_CODE, A.DESCRIPTION, A.AMOUNT, A.TYPE
  FROM  CASHBANKRECMASTER A
INNER JOIN COA B ON A.COA_ID = B.COA_ID
        WHERE A.DAATE BETWEEN '" + dtpDate + @"' AND '" + dtpDate.AddHours(23).AddMinutes(59).AddSeconds(59) + @"'
        ORDER BY [DATE] DESC";



--CREATE TABLE CASH_VOUCHER(
--ID INT IDENTITY(1,1) PRIMARY KEY,
--VOUCHER_TYPE CHAR,
--VOUCHER_NUMBER NVARCHAR(50),
--[DATE] DATETIME,
--ACCOUNT_ID INT,
--[DESCRIPTION] NVARCHAR(MAX),
--AMOUNT FLOAT,
--CREATED_BY INT,
--CREATION_DATE DATETIME,
--MODIFIED_BY INT,
--MODIFICATION_DATE DATETIME
--)

SELECT* FROM BANK_VOUCHER
DROP TABLE BANK_VOUCHER
CREATE TABLE BANK_VOUCHER(
ID INT IDENTITY(1,1) PRIMARY KEY,
VOUCHER_TYPE CHAR,
VOUCHER_NUMBER NVARCHAR(50),
[DATE] DATETIME,
BANK_ID INT,
ACCOUNT_ID INT,
[DESCRIPTION] NVARCHAR(MAX),
AMOUNT FLOAT,
CREATED_BY INT,
CREATION_DATE DATETIME,
MODIFIED_BY INT,
MODIFICATION_DATE DATETIME
)

SELECT A.ID,A.[DATE],A.VOUCHER_TYPE,A.VOUCHER_NUMBER,A.ACCOUNT_ID,
B.COA_NAME AS [ACCOUNT NAME],A.[DESCRIPTION],A.AMOUNT
FROM CASH_VOUCHER A
INNER JOIN COA B ON A.ACCOUNT_ID = B.COA_ID

SELECT ISNULL(MAX(ID),0)+1 FROM CASH_VOUCHER

--CREATE TABLE SERVICE_TYPES(
--ID INT IDENTITY(1,1) PRIMARY KEY,
--SERVICE_TYPE NVARCHAR(100),
--CREATED_BY INT,
--CREATION_DATE DATETIME,
--MODIFIED_BY INT,
--MODIFICATION_DATE DATETIME
--)

--ALTER TABLE SALE_MASTER ADD IS_POSTED CHAR

--UPDATE SALE_MASTER SET IS_POSTED = 'Y'

--ALTER TABLE SALE_DETAIL ADD COST_RATE FLOAT
--UPDATE SALE_DETAIL SET COST_RATE = 0

--ALTER TABLE GENERAL_VOUCHER_D ADD CREDIT_ID INT

--CREATE TABLE SALE_EXPENSE(
--ID INT IDENTITY(1,1) PRIMARY KEY,
--SALE_MASTER_ID INT,
--[DATE] DATETIME,
--VENDOR_ID INT,
--SERVICE_ID INT,
--[DESCRIPTION] NVARCHAR(MAX),
--[TYPE] CHAR,
--AMOUNT FLOAT,
--CREATION_DATE DATETIME,
--CREATED_BY INT,
--MODIFICATION_DATE DATETIME,
--MODIFIED_BY INT
--)


ALTER TABLE SALE_MASTER ADD REFERENCE NVARCHAR(MAX)
UPDATE SALE_MASTER SET REFERENCE = ''