--INSERT INTO COA VALUES (38,9,'040030001','OTHER INCOME',0,'C',0,GETDATE(),1,NULL,NULL,1)
--INSERT INTO COA VALUES (38,9,'040030002','LOSS ON INVENTORY',0,'C',0,GETDATE(),1,NULL,NULL,1)
--INSERT INTO COA VALUES (9,19,'010020001','ADJUSTMENT INVENTORY',0,'D',0,GETDATE(),1,NULL,NULL,1)
--INSERT INTO PRODUCT_CATEGORY VALUES ('SUN FLAME',0,1,GETDATE(),NULL,NULL,1)

--10
--2010

--INSERT INTO PRODUCT_MASTER
--SELECT PRODUCT_CODE,[SUN FLAME]+' - '+PRODUCT_NAME,0,0,1,GETDATE(),NULL,NULL,10,NULL,NULL,NULL,
--0,0,0,0,[LIST RATE],[NET RATE]
--FROM PRODUCTs_15_2
--WHERE [SUN FLAME] IS NOT NULL

USE [STOVE_MANAGEMENT_SYSTEM]
GO
/****** Object:  Table [dbo].[Products_15_2]    Script Date: 2/15/2021 1:28:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products_15_2](
	[PRODUCT_CODE] [nvarchar](255) NULL,
	[PRODUCT_NAME] [nvarchar](255) NULL,
	[MARSHAL ] [nvarchar](255) NULL,
	[BLUE FLAME ] [nvarchar](255) NULL,
	[MEHRAN ] [nvarchar](255) NULL,
	[PAK FAMOUS] [nvarchar](255) NULL,
	[NATURAL ] [nvarchar](255) NULL,
	[PAK] [nvarchar](255) NULL,
	[SUN FLAME] [nvarchar](255) NULL,
	[LIST RATE] [float] NULL,
	[NET RATE] [float] NULL
) ON [PRIMARY]

GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'HOB 27"', N'HOB - 27" 3 BURNER HOB  - M.S', N'MARSHAL ', N'BLUE FLAME', N'MEHRAN', N'PAK FAMOUS', NULL, N'PAK', N'SUN FLAME', 3800, 3800)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'HOB 27"', N'HOB - 27" 3 BURNER  - BRASS', N'MARSHAL ', N'BLUE FLAME', N'MEHRAN', N'PAK FAMOUS', NULL, N'PAK', N'SUN FLAME', 4050, 4050)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'HOB 34"', N'HOB - 34" 5 BURNER HOB  - M.S', N'MARSHAL ', N'BLUE FLAME', N'MEHRAN', N'PAK FAMOUS', NULL, N'PAK', N'SUN FLAME', 5500, 5500)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'HOB 34"', N'HOB - 34" 5 BURNER   - BRASS', N'MARSHAL ', N'BLUE FLAME', N'MEHRAN', N'PAK FAMOUS', NULL, N'PAK', N'SUN FLAME', 5850, 5850)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 001', N' SMALL - ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 1250, 1200)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 001', N' SMALL - M.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 1280, 1230)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 002', N' MEDIUM ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 1450, 1400)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 002', N'MEDIUM - M.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 1530, 1480)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 003', N' MEDIUM TWIN ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 1750, 1700)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 003', N' MEDIUM TWIN - M.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 1830, 1780)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 004', N' DOUBLE - ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2050, 2000)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 004', N' DOUBLE - M.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2100, 2050)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 004', N' DOUBLE - S.S ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2550, 2500)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 004', N' DOUBLE - S.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2550, 2500)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 005', N' TOASTER - ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2450, 2400)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 005', N' TOASTER - M.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2500, 2450)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 005', N' TOASTER - S.S ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2950, 2900)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 005', N' TOASTER - S.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2950, 2900)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 006', N' FAMILY - ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2350, 2300)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 006', N' FAMILY - M.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2450, 2400)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 006', N' FAMILY - S.S', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2850, 2800)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 006', N' FAMILY - S.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2850, 2800)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 007', N'FAMILY TWIN - ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2600, 2550)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 007', N'FAMILY TWIN - M.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 2700, 2650)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 007', N'FAMILY TWIN - S.S', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 3100, 3050)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 007', N'FAMILY TWIN - S.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 3100, 3050)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 008', N' TWIN TWIN DOUBLE - ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 3150, 3100)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 008', N' TWIN TWIN DOUBLE - M.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 3300, 3250)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 008', N' TWIN TWIN DOUBLE - S.S', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 3650, 3600)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 008', N' TWIN TWIN DOUBLE - S.S C.I GRILL', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 3750, 3700)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 009', N'FAMILY TWIN TOASTER - ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 3150, 3100)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 009', N'FAMILY TWIN TOASTER - M.S C.I GRILL ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 3250, 3200)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 009', N'FAMILY TWIN TOASTER - S.S ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 3650, 3600)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 009', N'FAMILY TWIN TOASTER - S.S C.I GRILL ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, NULL, N'SUN FLAME', 3650, 3600)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 010', N' NATURAL DOUBLE - M.S ', NULL, NULL, NULL, NULL, N'NATURAL ', NULL, NULL, 1800, 1750)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 010', N' NATURAL DOUBLE - M.S C.I GRILL', NULL, NULL, NULL, NULL, N'NATURAL ', NULL, NULL, 1850, 1800)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 103', N'HOB - CHINA MODEL NATURAL   - M.S', NULL, NULL, NULL, N'PAK FAMOUS', N'NATURAL ', NULL, N'SUN FLAME', 3300, 3300)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 104', N'HOB - CHINA MODEL NATURAL   - M.S', NULL, NULL, NULL, N'PAK FAMOUS', N'NATURAL ', NULL, N'SUN FLAME', 3500, 3500)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 203', N'HOB - CHINA TOP  NATURAL  - M.S', NULL, NULL, NULL, N'PAK FAMOUS', N'NATURAL ', NULL, N'SUN FLAME', 3700, 3700)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 203', N'HOB - CHINA TOP BLACK ', NULL, NULL, NULL, NULL, N'NATURAL ', NULL, NULL, 3700, 3700)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 204', N'HOB - CHINA TOP NATURAL - M.S', NULL, NULL, NULL, N'PAK FAMOUS', N'NATURAL ', NULL, N'SUN FLAME', 4000, 4000)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 204', N'HOB - CHINA TOP BLACK ', NULL, NULL, NULL, NULL, N'NATURAL ', NULL, NULL, 4000, 4000)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 303 ', N'HOB - HOB CHINA TOP  - M.S', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4000, 4000)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 303 ', N'HOB - CHINA TOP BLACK  ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4000, 4000)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 304', N'HOB - HOB CHINA TOP  - M.S', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4200, 4200)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 304', N'HOB - CHINA TOP BLACK  ', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4200, 4200)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 305', N'HOB - HOB CHINA TOP  - M.S', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4600, 4600)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 305', N'HOB - CHINA TOP BLACK  - BRASS', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4600, 4600)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 403', N'HOB - HOB CHINA TOP  - M.S', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4200, 4200)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 403', N'HOB - CHINA TOP BLACK', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4200, 4200)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 404', N'HOB - HOB CHINA TOP  - M.S', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4400, 4400)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 404', N'HOB - CHINA TOP BLACK', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4400, 4400)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 405', N'HOB - HOB CHINA TOP  - M.S', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4800, 4800)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 405', N'HOB - CHINA TOP BLACK  - BRASS', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4800, 4800)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 406', N'HOB - HOB CHINA TOP  - M.S', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4600, 4600)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 406', N'HOB - CHINA TOP BLACK', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 4600, 4600)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 407', N'HOB - HOB CHINA TOP  - M.S', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 5000, 5000)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 407', N'HOB - CHINA TOP BLACK  - BRASS', N'MARSHAL ', N'BLUE FLAME ', N'MEHRAN ', N'PAK FAMOUS', NULL, N'PAK ', N'SUN FLAME', 5000, 5000)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 444', N'FANCY - DOUBLE MS - M.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 2450, 2350)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 444', N'FANCY - DOUBLE MS - M.S BRASS', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 2700, 2600)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 444', N'FANCY - DOUBLE MS - S.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 2700, 2600)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 444', N'FANCY - DOUBLE MS - S.S BRASS BURNER', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 2950, 2850)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 555', N'FANCY - 3 BURNER MS - M.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3050, 2950)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 555', N'FANCY - 3 BURNER JUMBO - M.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3550, 3450)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 555', N'FANCY - 3 BURNER MS - M.S BRASS', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3300, 3200)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 555', N'FANCY - 3 BURNER JUMBO - M.S BRASS', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3900, 3800)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 555', N'FANCY - 3 BURNER MS - S.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 2800, 2700)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 555', N'FANCY - 3 BURNER JUMBO - S.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 2800, 2700)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 555', N'FANCY - 3 BURNER MS - S.S BRASS BURNER', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3050, 2950)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 555', N'FANCY - 3 BURNER JUMBO - S.S BRASS BURNER', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3550, 3550)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 555', N'3 BURNER PUNJAB JUMBO ', NULL, NULL, N'MEHRAN ', NULL, NULL, NULL, NULL, 3550, 3450)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 777', N'FANCY - FAMILY TWIN DOUBLE  - M.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3050, 2950)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 777', N'FANCY - FAMILY TWIN JUMBO  - M.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3500, 3400)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 777', N'FANCY - FAMILY TWIN DOUBLE  - M.S BRASS', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3050, 3050)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 777', N'FANCY - FAMILY TWIN JUMBO  - M.S BRASS', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3400, 3300)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 777', N'FANCY - FAMILY TWIN DOUBLE  - S.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 2950, 3050)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 777', N'FANCY - FAMILY TWIN JUMBO  - S.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3150, 3050)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 777', N'FANCY - FAMILY TWIN DOUBLE  - S.S BRASS BURNER', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 2950, 3050)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 777', N'FANCY - FAMILY TWIN JUMBO  - S.S BRASS BURNER', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3750, 3650)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 888', N'FANCY - TWIN TWIN DOUBLE  - M.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3350, 3250)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 888', N'FANCY - TWIN+TWIN JUMBO - M.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3850, 3750)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 888', N'FANCY - TWIN TWIN DOUBLE  - M.S BRASS', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3450, 3350)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 888', N'FANCY - TWIN+TWIN JUMBO - M.S BRASS', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3950, 3950)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 888', N'FANCY - TWIN TWIN DOUBLE  - S.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3350, 3250)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 888', N'FANCY - TWIN+TWIN JUMBO - S.S', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3850, 3750)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 888', N'FANCY - TWIN TWIN DOUBLE  - S.S BRASS BURNER', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3450, 3350)
GO
INSERT [dbo].[Products_15_2] ([PRODUCT_CODE], [PRODUCT_NAME], [MARSHAL ], [BLUE FLAME ], [MEHRAN ], [PAK FAMOUS], [NATURAL ], [PAK], [SUN FLAME], [LIST RATE], [NET RATE]) VALUES (N'MDL 888', N'FANCY - TWIN+TWIN JUMBO - S.S BRASS BURNER', N'MARSHAL ', N'BLUEFLAME ', N'MEHRAN ', N'PAK FAMOUS', N'NATURAL ', N'PAK', N'SUN FLAME', 3950, 3950)
GO


