
SELECT * FROM SALE_MASTER
SELECT * FROM SALE_DETAIL

	SELECT A.SALE_MASTER_ID AS [ID],A.INVOICE_NO AS [INVOICE #],
	A.[DATE],B.COA_NAME AS [CUSTOMER],A.REFERENCE,A.[DESCRIPTION],
	A.CREDIT_DAYS,A.CUSTOMER_ID,TERM
	FROM SALE_MASTER A
	INNER JOIN COA B ON A.CUSTOMER_ID = B.COA_ID
	ORDER BY SALE_MASTER_ID DESC

	SELECT A.ITEM_ID,   
	B.PRODUCT_NAME AS [PRODUCT], 
	A.QTY,
	A.RATE, 
	(A.QTY * A.RATE) AS [TOTAL]
	FROM SALE_DETAIL A
	INNER JOIN PRODUCT_MASTER B ON A.ITEM_ID = B.PM_ID

