SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Abdul Haseeb
-- Create date: 25-09-2026
-- Description:	To find if any record exists against brand ID
-- =============================================
CREATE FUNCTION CheckBrandRecords 
(
	@ID int
)
RETURNS char
AS
BEGIN
	DECLARE @IS_EXISTS CHAR = 'N';

	IF EXISTS (SELECT TOP 1 C.P_CATEGORY_ID
	FROM SALE_DETAIL A
	INNER JOIN PRODUCT_MASTER B ON A.ITEM_ID = B.PM_ID
	INNER JOIN PRODUCT_CATEGORY C ON B.BRAND_ID = C.P_CATEGORY_ID
	WHERE C.P_CATEGORY_ID = @ID)
	BEGIN 
		SET @IS_EXISTS = 'Y';
	END

	IF EXISTS (SELECT TOP 1 C.P_CATEGORY_ID
	FROM PRODUCTION_DETAIL A
	INNER JOIN PRODUCT_MASTER B ON A.PRODUCT_MASTER_ID = B.PM_ID
	INNER JOIN PRODUCT_CATEGORY C ON B.BRAND_ID = C.P_CATEGORY_ID
	WHERE C.P_CATEGORY_ID = @ID)
	BEGIN 
		SET @IS_EXISTS = 'Y';
	END

	RETURN @IS_EXISTS;
END
GO

