CREATE TABLE PAYMENT_REGISTER(
ID INT IDENTITY(1,1) PRIMARY KEY,
[DATE] DATETIME,
RECEIVING_ACCOUNT_ID INT,
PAYMENT_ACCOUNT_ID INT,
AMOUNT FLOAT,
TRANSACTION_TYPE CHAR,
CREATED_BY INT,
CREATION_DATE DATETIME,
MODIFIED_BY INT,
MODIFICATION_DATE DATETIME
)

