--alter table coa add CITY_NAME nvarchar(max)
--truncate table ledgers
--update coa set mobile = '',[address] = '', credit_days = 0, city_name = ''
--delete from sale_master where sale_master_id = 1
--delete FROM SALE_DETAIL where sale_master_id = 1
--ALTER TABLE SALE_MASTER ADD CUSTOMER_ADDRESS NVARCHAR(MAX) NOT NULL DEFAULT ''
--ALTER TABLE SALE_MASTER ADD SHIP_TO NVARCHAR(MAX) NOT NULL DEFAULT ''
--ALTER TABLE SALE_MASTER ADD SHIPPING_ADDRESS NVARCHAR(MAX) NOT NULL DEFAULT ''
--ALTER TABLE SALE_MASTER ADD BORI_EXPENSE FLOAT NOT NULL DEFAULT '0'
--ALTER TABLE SALE_MASTER ADD CARTON_EXPENSE FLOAT NOT NULL DEFAULT '0'
select * from coa
SELECT * FROM CONTROL_ACCOUNT where ca_id in ( 5,6,10)
select * from ACCOUNT_GROUP

SELECT * FROM PRODUCT_MASTER

SELECT A.BRAND_ID,B.P_CATEEGORY_NAME AS [BRAND],A.PM_ID,A.PRODUCT_CODE AS [PRODUCT CODE],A.PRODUCT_NAME AS [PRODUCT NAME],
            A.OPENING_QTY AS [OPENING_QUANTITY],A.OPENING_RATE AS RATE,A.GROSS_WEIGHT AS [BUNDLE PCS],A.NET_WEIGHT AS [TOTAL BUNDLES]
            FROM PRODUCT_MASTER A
            INNER JOIN PRODUCT_CATEGORY B ON A.BRAND_ID = B.P_CATEGORY_ID
            ORDER BY A.PM_ID DESC

