ALTER TABLE PRODUCTION_MASTER ADD [INVOICE_NO] NVARCHAR(MAX) NOT NULL DEFAULT ''
ALTER TABLE PRODUCTION_MASTER ADD [DESCRIPTION] NVARCHAR(MAX) NOT NULL DEFAULT ''
ALTER TABLE PRODUCTION_DETAIL ADD [TOTAL_BUNDLE] FLOAT NOT NULL DEFAULT 0
ALTER TABLE PRODUCTION_DETAIL ADD [BUNDLE_PCS] FLOAT NOT NULL DEFAULT 0
ALTER TABLE PRODUCTION_DETAIL ADD [RATE] FLOAT NOT NULL DEFAULT 0
ALTER TABLE PRODUCTION_DETAIL ADD [TOTAL] FLOAT NOT NULL DEFAULT 0